-- Read-only Oracle acceptance checks after installing 015-credit-cards.sql
-- (or the former feature-branch filename 011-credit-cards.sql).
-- Run as the Moneybags schema owner. All exception queries should return zero rows.
SET PAGESIZE 100
SET LINESIZE 220

-- The module requires six tables and three enabled immutability/terms triggers.
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'M11_CC_%' ORDER BY TABLE_NAME;
SELECT TRIGGER_NAME,STATUS FROM USER_TRIGGERS WHERE TRIGGER_NAME LIKE 'CC_%';
SELECT OBJECT_NAME,OBJECT_TYPE,STATUS FROM USER_OBJECTS WHERE OBJECT_NAME LIKE 'CC_%' AND STATUS<>'VALID';

-- Credit projections must agree with the immutable card subledger.
SELECT C.CARD_ID,C.PRINCIPAL_BALANCE,C.INTEREST_BALANCE,
       COALESCE(SUM(E.PRINCIPAL_DELTA),0) ENTRY_PRINCIPAL,
       COALESCE(SUM(E.INTEREST_DELTA),0) ENTRY_INTEREST
FROM M11_CC_CARD C LEFT JOIN M11_CC_ENTRY E ON E.CARD_ID=C.CARD_ID
GROUP BY C.CARD_ID,C.PRINCIPAL_BALANCE,C.INTEREST_BALANCE
HAVING C.PRINCIPAL_BALANCE<>COALESCE(SUM(E.PRINCIPAL_DELTA),0)
    OR C.INTEREST_BALANCE<>COALESCE(SUM(E.INTEREST_DELTA),0);

-- Card receivables must agree with their authoritative M05 journals.
SELECT C.CARD_ID,C.PRINCIPAL_BALANCE+C.INTEREST_BALANCE CARD_BALANCE,
       COALESCE(SUM(CASE WHEN G.GL_CODE='CC_RECEIVABLE' THEN
         CASE WHEN P.ENTRY_SIDE='DR' THEN P.AMOUNT ELSE -P.AMOUNT END ELSE 0 END),0) GL_BALANCE
FROM M11_CC_CARD C LEFT JOIN M11_CC_ENTRY E ON E.CARD_ID=C.CARD_ID
LEFT JOIN M05_GL_POSTING P ON P.JOURNAL_ID=E.JOURNAL_ID
LEFT JOIN M05_GL_ACCOUNT G ON G.GL_ACCOUNT_ID=P.GL_ACCOUNT_ID
GROUP BY C.CARD_ID,C.PRINCIPAL_BALANCE,C.INTEREST_BALANCE
HAVING C.PRINCIPAL_BALANCE+C.INTEREST_BALANCE<>
  COALESCE(SUM(CASE WHEN G.GL_CODE='CC_RECEIVABLE' THEN
    CASE WHEN P.ENTRY_SIDE='DR' THEN P.AMOUNT ELSE -P.AMOUNT END ELSE 0 END),0);

SELECT E.CARD_ID,E.ENTRY_ID,V.JOURNAL_ID FROM M11_CC_ENTRY E
JOIN M05_V_GL_JOURNAL_CONTROL V ON V.JOURNAL_ID=E.JOURNAL_ID WHERE V.IS_BALANCED='N';

-- Product terms and decisions must retain independent maker/checker identities.
SELECT PRODUCT_ID FROM M11_CC_PRODUCT WHERE STATUS IN ('APPROVED','RETIRED') AND (CHECKER_ID IS NULL OR CHECKER_ID=MAKER_ID);
SELECT APPLICATION_ID FROM M11_CC_APPLICATION WHERE STATUS='APPROVED' AND (CHECKER_ID IS NULL OR CHECKER_ID=MAKER_ID OR APPROVED_LIMIT IS NULL);

SELECT GL_CODE,ACCOUNT_CLASS,NORMAL_SIDE,CURRENCY_CODE,ACTIVE_FLAG FROM M05_GL_ACCOUNT
WHERE GL_CODE IN ('CC_RECEIVABLE','CC_SETTLEMENT','CC_INTEREST') ORDER BY GL_CODE;

-- Confirm real row-lock behavior in two independent Oracle sessions as part of
-- acceptance: concurrent purchases above a shared remaining limit must allow
-- only one posting; repeat request keys must create one journal and one entry.
