-- Read-only acceptance after integrating main's teller/RBI migrations 011-014 and credit cards 015.
-- A former completed 011-credit-cards.sql installation already supplies the M11_CC_* objects.
-- Run with F5 as the application schema owner; this file never installs or changes objects.
SET LINESIZE 220
SET PAGESIZE 100

-- Expect no rows. Table ALTERs may invalidate existing triggers until they are recompiled.
SELECT OBJECT_NAME, OBJECT_TYPE FROM USER_OBJECTS WHERE STATUS='INVALID' ORDER BY OBJECT_TYPE, OBJECT_NAME;
SELECT NAME, TYPE, LINE, POSITION, TEXT FROM USER_ERRORS ORDER BY NAME, SEQUENCE;

-- Expect all six main teller/RBI tables, plus the four linkage columns below.
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN
 ('MBX_BRANCH_VAULT','MBX_TILL_ALLOCATION','MBX_TILL_CASH_RETURN',
  'MBX_RBI_CASH_DELIVERY','MBX_TILL_REPLENISHMENT','MBX_RBI_RESERVE_OPENING') ORDER BY TABLE_NAME;
SELECT TABLE_NAME, COLUMN_NAME FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME IN ('M07_SETTLEMENT_EVIDENCE','M07_CENTRAL_TREASURY_LEDGER')
 AND COLUMN_NAME IN ('CASH_DELIVERY_ID','RESERVE_OPENING_ID') ORDER BY TABLE_NAME, COLUMN_NAME;

-- Expect five ENABLED / VALID rows: three card triggers and two existing treasury triggers.
SELECT T.TRIGGER_NAME, T.STATUS AS ENABLED_STATUS, O.STATUS AS COMPILE_STATUS
 FROM USER_TRIGGERS T JOIN USER_OBJECTS O ON O.OBJECT_NAME=T.TRIGGER_NAME AND O.OBJECT_TYPE='TRIGGER'
 WHERE T.TRIGGER_NAME IN ('CC_PRODUCT_TERMS_IMMUTABLE','CC_ENTRY_IMMUTABLE','CC_STATEMENT_IMMUTABLE',
 'M07_TRG_SETTLEMENT_EVIDENCE_IMMUTABLE','M07_TRG_TREASURY_LEDGER_IMMUTABLE') ORDER BY T.TRIGGER_NAME;

-- Expect no rows from each financial mismatch query.
SELECT JOURNAL_ID FROM M05_V_GL_JOURNAL_CONTROL WHERE IS_BALANCED<>'Y';
SELECT RESERVE_ACCOUNT_ID FROM M07_V_RESERVE_POSITION_RECON WHERE IS_MATCHED<>'Y';
SELECT V.BRANCH_CODE FROM MBX_BRANCH_VAULT V
 WHERE V.CASH_BALANCE<>NVL((SELECT SUM(CASE WHEN P.ENTRY_SIDE='DR' THEN P.AMOUNT ELSE -P.AMOUNT END)
 FROM M05_GL_POSTING P WHERE P.GL_ACCOUNT_ID=V.VAULT_GL_ID),0);

-- Run acceptance/credit-cards.sql separately for the six M11 tables, card GL configuration,
-- independent approval records and card projection/entry/receivable mismatch checks.
