-- Synthetic ALPHA fixture only. Let MCP Demo A initiate its own internal transfers.
-- Run after 008; this does not grant transfer authority to Demo B or real users.
MERGE INTO M01_IAM_ROLE R
USING (SELECT 'MCP_DEMO_A_TRANSFER' ROLE_CODE FROM DUAL) S
ON (R.ROLE_CODE=S.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_ID,ROLE_CODE,DISPLAY_NAME,STATUS,SENSITIVE_FLAG)
VALUES (LOWER(RAWTOHEX(SYS_GUID())),S.ROLE_CODE,'MCP Demo A transfer','ACTIVE','N');

MERGE INTO M01_IAM_ROLE_PERMISSION RP
USING (SELECT R.ROLE_ID,P.PERMISSION_ID FROM M01_IAM_ROLE R CROSS JOIN M01_IAM_PERMISSION P
       WHERE R.ROLE_CODE='MCP_DEMO_A_TRANSFER' AND P.PERMISSION_CODE='TXN_POST') S
ON (RP.ROLE_ID=S.ROLE_ID AND RP.PERMISSION_ID=S.PERMISSION_ID)
WHEN NOT MATCHED THEN INSERT (ROLE_ID,PERMISSION_ID) VALUES (S.ROLE_ID,S.PERMISSION_ID);

MERGE INTO M01_IAM_USER_ROLE UR
USING (SELECT U.USER_ID,R.ROLE_ID FROM M01_IAM_USER U CROSS JOIN M01_IAM_ROLE R
       WHERE U.USERNAME='mcp_demo_customer_a' AND R.ROLE_CODE='MCP_DEMO_A_TRANSFER') S
ON (UR.USER_ID=S.USER_ID AND UR.ROLE_ID=S.ROLE_ID AND UR.STATUS='ACTIVE')
WHEN NOT MATCHED THEN INSERT (ASSIGNMENT_ID,USER_ID,ROLE_ID,SCOPE_TYPE,STATUS,VALID_FROM)
VALUES (LOWER(RAWTOHEX(SYS_GUID())),S.USER_ID,S.ROLE_ID,'SELF','ACTIVE',SYSTIMESTAMP);

UPDATE M01_IAM_USER SET ENTITLEMENT_VERSION=ENTITLEMENT_VERSION+1,ROW_VERSION=ROW_VERSION+1,
  UPDATED_AT=SYSTIMESTAMP WHERE USERNAME='mcp_demo_customer_a';
COMMIT;
