-- Synthetic ALPHA fixture only: enable WEB internal transfers for the product
-- used by MCP Demo A/B. Restrict the rule to that product version and cap daily
-- transfer value at the demo account's original INR 500 opening deposit.
DECLARE
  account_count NUMBER;
  fixture_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO account_count FROM M04_BANK_ACCOUNT WHERE PRODUCT_VERSION_ID=32;
  SELECT COUNT(*) INTO fixture_count FROM M04_BANK_ACCOUNT A
    JOIN M03_PM_PRODUCT P ON P.PRODUCT_ID=A.PRODUCT_ID
    WHERE A.PRODUCT_VERSION_ID=32 AND P.PRODUCT_CODE='MCP-ALPHA-SAV'
      AND ((A.ACCOUNT_ID=3 AND A.ACCOUNT_NUMBER='MCPALPHA0001') OR
           (A.ACCOUNT_ID=4 AND A.ACCOUNT_NUMBER='MCPALPHA0002'));
  IF account_count<>2 OR fixture_count<>2 THEN
    RAISE_APPLICATION_ERROR(-20001,'Synthetic MCP product contains unexpected accounts');
  END IF;
END;
/
MERGE INTO M03_PM_TRANSACTION_RULE R
USING (SELECT PRODUCT_VERSION_ID FROM M04_BANK_ACCOUNT
       WHERE ACCOUNT_ID=3 AND ACCOUNT_NUMBER='MCPALPHA0001') S
ON (R.PRODUCT_VERSION_ID=S.PRODUCT_VERSION_ID AND R.RULE_CODE='MCP_TRANSFER_WEB')
WHEN NOT MATCHED THEN INSERT
  (PRODUCT_VERSION_ID,RULE_CODE,OPERATION_CODE,CHANNEL_CODE,DIRECTION_CODE,ACTION_CODE,PRIORITY_NO)
VALUES (S.PRODUCT_VERSION_ID,'MCP_TRANSFER_WEB','INTERNAL_TRANSFER','WEB','BOTH','ALLOW',1);

MERGE INTO M03_PM_LIMIT_RULE L
USING (SELECT PRODUCT_VERSION_ID FROM M04_BANK_ACCOUNT
       WHERE ACCOUNT_ID=3 AND ACCOUNT_NUMBER='MCPALPHA0001') S
ON (L.PRODUCT_VERSION_ID=S.PRODUCT_VERSION_ID AND L.RULE_CODE='MCP_TRANSFER_DAY')
WHEN NOT MATCHED THEN INSERT
  (PRODUCT_VERSION_ID,RULE_CODE,OPERATION_CODE,PERIOD_CODE,MIN_AMOUNT,MAX_AMOUNT,MAX_COUNT,CURRENCY_CODE)
VALUES (S.PRODUCT_VERSION_ID,'MCP_TRANSFER_DAY','INTERNAL_TRANSFER','DAY',0.01,500,20,'INR');

MERGE INTO M05_GL_PRODUCT_MAPPING M
USING (SELECT P.PRODUCT_VERSION_ID,P.GL_ACCOUNT_ID,P.EFFECTIVE_FROM,P.CREATED_BY
       FROM M05_GL_PRODUCT_MAPPING P JOIN M04_BANK_ACCOUNT A
         ON A.PRODUCT_VERSION_ID=P.PRODUCT_VERSION_ID
       WHERE A.ACCOUNT_ID=3 AND A.ACCOUNT_NUMBER='MCPALPHA0001'
         AND P.POSTING_TYPE='PAYMENT' AND P.GL_ROLE_CODE='CUSTOMER_LIABILITY'
         AND P.STATUS='ACTIVE' AND P.EFFECTIVE_TO IS NULL) S
ON (M.PRODUCT_VERSION_ID=S.PRODUCT_VERSION_ID AND M.POSTING_TYPE='TRANSFER'
    AND M.GL_ROLE_CODE='CUSTOMER_LIABILITY' AND M.EFFECTIVE_FROM=S.EFFECTIVE_FROM)
WHEN NOT MATCHED THEN INSERT
  (PRODUCT_VERSION_ID,POSTING_TYPE,GL_ROLE_CODE,GL_ACCOUNT_ID,EFFECTIVE_FROM,CREATED_BY)
VALUES (S.PRODUCT_VERSION_ID,'TRANSFER','CUSTOMER_LIABILITY',S.GL_ACCOUNT_ID,S.EFFECTIVE_FROM,S.CREATED_BY);
COMMIT;
