-- Read-only acceptance diagnostics. Run against the intended application schema.
-- Zero rows is expected for invalid/disabled controls and accounting exceptions.
SELECT OBJECT_NAME,OBJECT_TYPE,STATUS FROM USER_OBJECTS
 WHERE (OBJECT_NAME LIKE 'M0%' OR OBJECT_NAME LIKE 'M10%' OR OBJECT_NAME LIKE 'MBX%') AND STATUS<>'VALID';
SELECT TABLE_NAME,CONSTRAINT_NAME,STATUS,VALIDATED FROM USER_CONSTRAINTS
 WHERE (TABLE_NAME LIKE 'M0%' OR TABLE_NAME LIKE 'M10%' OR TABLE_NAME LIKE 'MBX%')
 AND (STATUS<>'ENABLED' OR VALIDATED<>'VALIDATED');
SELECT TRIGGER_NAME,STATUS FROM USER_TRIGGERS
 WHERE (TABLE_NAME LIKE 'M0%' OR TABLE_NAME LIKE 'M10%' OR TABLE_NAME LIKE 'MBX%') AND STATUS<>'ENABLED';
SELECT TABLE_NAME FROM USER_TABLES
 WHERE TABLE_NAME LIKE 'M0%' OR TABLE_NAME LIKE 'M10%' OR TABLE_NAME LIKE 'MBX%' ORDER BY TABLE_NAME;
SELECT * FROM M05_V_GL_JOURNAL_CONTROL WHERE IS_BALANCED='N';
SELECT * FROM M05_V_ACCOUNT_POSITION_RECON WHERE IS_MATCHED='N';
SELECT ACCOUNT_ID FROM M04_BANK_ACCOUNT A
 WHERE LIFECYCLE_STATUS='ACTIVE' AND NOT EXISTS(SELECT 1 FROM M05_POSTING_FENCE F WHERE F.BANK_ACCOUNT_ID=A.ACCOUNT_ID);
SELECT USER_ID FROM MBX_CUSTOMER_SECRET WHERE LENGTH(SECRET_DIGEST)<>32;
SELECT REQUEST_ID FROM MBX_OVERRIDE_APPROVAL WHERE MAKER_ID=CHECKER_ID;
SELECT PUBLISH_STATUS,COUNT(*) EVENT_COUNT,MIN(OCCURRED_AT) OLDEST_EVENT FROM M05_OUTBOX_EVENT GROUP BY PUBLISH_STATUS;
SELECT PUBLISH_STATUS,COUNT(*) EVENT_COUNT,MIN(OCCURRED_AT) OLDEST_EVENT FROM M06_OUTBOX_EVENT GROUP BY PUBLISH_STATUS;
SELECT PUBLISH_STATUS,COUNT(*) EVENT_COUNT,MIN(OCCURRED_AT) OLDEST_EVENT FROM M07_OUTBOX_EVENT GROUP BY PUBLISH_STATUS;
SELECT PUBLISH_STATUS,COUNT(*) EVENT_COUNT,MIN(OCCURRED_AT) OLDEST_EVENT FROM M08_OUTBOX_EVENT GROUP BY PUBLISH_STATUS;
-- Expected: one enabled MBX_AUDIT_IMMUTABLE trigger. Original ledger/audit triggers
-- must also be reviewed against the supplied installer, not merely counted.
SELECT TRIGGER_NAME,STATUS FROM USER_TRIGGERS WHERE TRIGGER_NAME='MBX_AUDIT_IMMUTABLE';
