"""Generate an isolated H2 Oracle-mode fixture. Never execute this on Oracle.

Preserves table columns, keys and check constraints except Oracle-specific JSON checks.
Oracle triggers and function-based indexes require the separate Oracle acceptance suite.
"""
from pathlib import Path
import re

base = Path(__file__).resolve().parents[1]
source = '\n'.join(p.read_text(encoding='utf-8-sig') for p in sorted((base/'database').glob('*.sql')))
source = re.sub(r'/\*[\s\S]*?\*/|--[^\n]*', '', source)

def end_block(text, start):
    depth, quoted, i = 1, False, start+1
    while i < len(text):
        c = text[i]
        if c == "'":
            if quoted and i+1 < len(text) and text[i+1] == "'": i+=2; continue
            quoted = not quoted
        if not quoted:
            depth += (c == '(') - (c == ')')
            if depth == 0: return i
        i += 1
    raise ValueError('Unclosed DDL')

def adapt(s):
    s = re.sub(r'\((\d+)\s+CHAR\)', r'(\1)', s)
    s = s.replace('GENERATED BY DEFAULT ON NULL AS IDENTITY','GENERATED BY DEFAULT AS IDENTITY')
    s = re.sub(r'SYS_EXTRACT_UTC\((\w+)\)', r'CAST(\1 AS TIMESTAMP)', s)
    s = re.sub(r'\s+VIRTUAL\b','',s)
    s = re.sub(r'\b\w+\s+IS JSON\b','1=1',s)
    s = re.sub(r'\bSYS_GUID\(\)', 'RANDOM_UUID()', s)
    return s

tables={}
for m in re.finditer(r'^CREATE TABLE (\w+)\s*\(', source, re.M):
    end=end_block(source,m.end()-1)
    tables[m[1]]=adapt(source[m.start():end+1])+';'
parts=['-- H2 fixture only. Oracle is the authoritative schema.']
for m in re.finditer(r'^CREATE SEQUENCE (\w+)[^;]+;',source,re.M):
    parts.append(f'CREATE SEQUENCE {m[1]} START WITH 1;')
# Forward foreign keys are deferred until all table definitions exist.
fks=[]
for name, ddl in tables.items():
    inline=[]
    body=ddl[ddl.index('(')+1:-2]
    start=0;depth=0;quoted=False;items=[]
    for i,c in enumerate(body):
        if c=="'":quoted=not quoted
        if not quoted:
            depth+=(c=='(')-(c==')')
            if c==',' and depth==0:items.append(body[start:i]);start=i+1
    items.append(body[start:])
    for item in items:
        if re.search(r'^\s*CONSTRAINT.*?FOREIGN KEY',item,re.S):
            fks.append(f'ALTER TABLE {name} ADD '+item.strip()+';')
        elif ' REFERENCES ' in re.sub(r'\s+',' ',item):
            match=re.search(r'\s+REFERENCES\s+(\w+)\s*\(([^)]+)\)',item)
            if match:
                col=item.strip().split()[0]
                fks.append(f'ALTER TABLE {name} ADD FOREIGN KEY ({col}) REFERENCES {match[1]}({match[2]});')
                inline.append(item[:match.start()]+item[match.end():])
            else:inline.append(item)
        else:inline.append(item)
    parts.append(f'CREATE TABLE {name} ('+','.join(inline)+');')
for m in re.finditer(r'^ALTER TABLE \w+\s+[^;]+;',source,re.M):
    ddl=adapt(m[0])
    if 'FOREIGN KEY' in ddl: fks.append(ddl)
    else: parts.append(ddl)
parts.extend(fks)
for m in re.finditer(r'^INSERT ALL\s+[\s\S]*?SELECT 1 FROM DUAL;|^INSERT INTO [^;]+;',source,re.M):
    if m[0].startswith('INSERT ALL'):
        for row in re.finditer(r'INTO\s+(\w+)\s+VALUES\s*\(([^\n]+)\)',m[0]):
            parts.append(f'INSERT INTO {row[1]} VALUES ({row[2]});')
    else:
        parts.append(adapt(m[0]))
for m in re.finditer(r'^CREATE (?:OR REPLACE )?VIEW\s+[^;]+;',source,re.M):
    parts.append(adapt(m[0]))
out=base/'backend/src/main/resources/local-schema.sql'
out.write_text('\n\n'.join(parts),encoding='utf-8')
print(f'Generated {len(tables)} tables, {len(fks)} foreign keys: {out.name}')
