from pathlib import Path
import json
base=Path(__file__).resolve().parents[1]/'frontend'
p=base/'app.js';s=p.read_text(encoding='utf-8-sig')
s="import {bankingPages,bankingScreen,configureBanking,bindBankingForms} from './banking.js';\n"+s
s=s.replace("page:'dashboard'","page:'banking'")
s=s.replace("const icons=", "Object.entries(bankingPages).forEach(([k,v])=>titles[k]=v.title);\nconst icons=")
s=s.replace("const can=", "Object.entries(bankingPages).forEach(([k,v])=>icons[k]=v.icon);\nconst can=")
s=s.replace("const head=", "const router=await new Promise((resolve,reject)=>window.require(['ojs/ojcorerouter','ojs/ojurlparamadapter'],(CoreRouter,UrlParamAdapter)=>resolve(new CoreRouter([{path:'',redirect:'banking'},...Object.keys(titles).map(path=>({path}))],{urlAdapter:new UrlParamAdapter()})),reject));\nrouter.currentState.subscribe(({state:route})=>{state.page=route.path;if(document.querySelector('#content'))render();});\nawait router.sync();\nconst head=")
s=s.replace("if(!nav.some(n=>n.page===state.page))", "for(const [page,config] of Object.entries(bankingPages))if((!config.permission||can(config.permission))&&!nav.some(n=>n.page===page))nav.push({page,label:config.title});\n  nav.sort((a,b)=>a.page==='banking'?-1:b.page==='banking'?1:0);\n  if(!nav.some(n=>n.page===state.page))")
s=s.replace("if(!can('IAM_USER_READ'))state.page='security';", "if(!can('IAM_USER_READ')&&state.page==='dashboard')state.page='banking';")
s=s.replace("try{let html;switch(state.page)", "try{let html;if(bankingPages[state.page])html=await bankingScreen(state.page);else switch(state.page)")
s=s.replace('bindForms();bindDomainForms();','bindForms();bindDomainForms();bindBankingForms();')
s=s.replace("case'nav':state.page=id;await render();break;","case'nav':await router.go({path:id});break;")
s=s.replace('configureDomains(render);','configureDomains(render);\nconfigureBanking(render);')
s=s.replace('Modules 01–03','Integrated banking').replace('Identity, Customers & Products','All banking workspaces').replace('COLLEGE BANKING PROJECT','INTEGRATED BANKING WORKSPACE').replace('College banking project','Money Bags')
s=s.replace('IDENTITY & ACCESS MANAGEMENT','MONEY BAGS CORE BANKING')
s=s.replace("await api(checker?'/iam/setup/checker':'/iam/users'", "const created=await api(checker?'/iam/setup/checker':'/customer-access/users'")
s=s.replace("toast(checker?'Checker created.","if(created.customerHash){await render();dialog('Save the customer hash',`<p class=\"notice\">Store this securely. It is shown only now, and must be combined with authorized login to disclose transaction details.</p><code>${esc(created.customerHash)}</code>`);return false;}toast(checker?'Checker created.")
p.write_text(s,encoding='utf-8')
p=base/'api.js';s=p.read_text()
s=s.replace("let session=null;", "let session=null;\nlet customerHash='';\nexport const getCustomerHash=()=>customerHash;\nexport const setCustomerHash=value=>{customerHash=String(value||'').trim();};")
s=s.replace('session=value;if(value)','session=value;if(!value)customerHash=\'\';if(value)')
s=s.replace("{method='GET',body}={}","{method='GET',body,headers:extraHeaders={}}={}")
s=s.replace("if(session?.accessToken)headers.Authorization", "Object.assign(headers,extraHeaders);if(customerHash)headers['X-Customer-Hash']=customerHash;if(method!=='GET'&&!headers['Idempotency-Key'])headers['Idempotency-Key']=body?.requestKey||body?.requestId||crypto.randomUUID();\n  if(session?.accessToken)headers.Authorization")
s=s.replace('let value;try{value=await response.json();}',"if(response.status===204)return null;\n  let value;try{value=await response.json();}")
s=s.replace('return value.data;','return Object.hasOwn(value,\'data\')?value.data:value;')
s=s.replace('headers:{Authorization:`Bearer ${session.accessToken}`}','headers:{Authorization:`Bearer ${session.accessToken}`,\'X-Customer-Hash\':customerHash}')
p.write_text(s,encoding='utf-8')
p=base/'server.mjs';s=p.read_text()
s=s.replace("['/app.js','app.js']","['/banking.js','banking.js'],['/comparisons.js','comparisons.js'],['/app.js','app.js']")
s=s.replace("url.pathname.startsWith('/api/')||url.pathname.startsWith('/actuator/')", "url.pathname.startsWith('/api/')||url.pathname.startsWith('/actuator/')||url.pathname.startsWith('/v3/api-docs')")
p.write_text(s,encoding='utf-8')
p=base/'domains.js';s=p.read_text().replace('./react-widgets.js','./comparisons.js');p.write_text(s,encoding='utf-8')
p=base/'package.json';data=json.loads(p.read_text());data['name']='moneybags-integrated-ui';data['description']='Unified Oracle JET and Knockout banking workspace';data['scripts']['build']='node tools/build.mjs';data['scripts']['check']='node --check app.js && node --check api.js && node --check banking.js && node --check server.mjs';p.write_text(json.dumps(data,indent=2),encoding='utf-8')
