import {bankingPages,bankingScreen,configureBanking,bindBankingForms} from './banking.js';
import {api,login,logout,refresh,getSession,saveSession} from './api.js';
import {esc,date,badge,field,select,reason,table,action,dialog,closeDialog,toast,errorText} from './ui.js';
import {jetReady,enhanceForms,validateJet,disposeJet} from './jet.js';
import {configureDomains,customersScreen,productsScreen,bindDomainForms} from './domains.js';
import {assistantWidget,bindAssistant,openAssistant,resetAssistant} from './assistant.js';
import {formatAmount,formatDecimal} from './presentation.js';
await jetReady;

const root=document.querySelector('#app');
const state={page:'banking',users:[],roles:[],permissions:[],requests:[],menus:[],userPage:0,search:'',status:'',detail:null,roleDetail:null,requestDetail:null,render:0};
const titles={dashboard:'Overview',users:'Users',roles:'Roles & permissions',access:'Access requests',audit:'Audit trail',security:'My security',customers:'Customers & KYC',products:'Product master',assistant:'Ask Moneybags'};
Object.entries(bankingPages).forEach(([k,v])=>titles[k]=v.title);
const icons={dashboard:'▦',users:'♙',roles:'◇',access:'⇄',audit:'≡',security:'⌑',customers:'♧',products:'▣',assistant:'✦'};
Object.entries(bankingPages).forEach(([k,v])=>icons[k]=v.icon);
const can=permission=>getSession()?.user?.permissions?.includes(permission);
const userName=id=>state.users.find(u=>u.userId===id)?.username||id;
const roleName=id=>state.roles.find(r=>r.roleId===id)?.displayName||id;
const permissionOptions=()=>[{value:'',label:'No permission required'},...state.permissions.map(p=>({value:p.permissionId,label:p.permissionCode}))];
const iso=value=>value?new Date(value).toISOString():null;
const localDate=value=>{const d=new Date(value||Date.now());return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const tags=values=>values.map(v=>`<span class="tag">${esc(v)}</span>`).join('')||'<span class="muted">None</span>';
const router=await new Promise((resolve,reject)=>window.require(['ojs/ojcorerouter','ojs/ojurlparamadapter'],(CoreRouter,UrlParamAdapter)=>resolve(new CoreRouter([{path:'',redirect:'banking'},...Object.keys(titles).map(path=>({path}))],{urlAdapter:new UrlParamAdapter()})),reject));
router.currentState.subscribe(({state:route})=>{if(!route)return;state.page=route.path==='assistant'?'banking':route.path;if(route.path==='assistant')openAssistant();if(document.querySelector('#content'))render();});
await router.sync();
const head=(title,subtitle,button='')=>`<div class="page-heading"><div><p class="eyebrow">IDENTITY & ACCESS</p><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div>${button}</div>`;
const panel=(title,body,buttons='')=>`<section class="panel"><div class="panel-heading"><h3>${esc(title)}</h3>${buttons}</div>${body}</section>`;
const detail=(name,value)=>`<div><dt>${esc(name)}</dt><dd>${esc(value??'—')}</dd></div>`;
function signIn(message=''){
  if(!getSession())resetAssistant();
  root.innerHTML=`<main class="login-layout"><section class="login-story"><div class="logo"><img src="/favicon.svg" alt="">Moneybags</div><div class="login-story-main"><p class="eyebrow">INTEGRATED BANKING</p><h1>Banking workspace</h1><p>Controlled access to customer, account, payment, lending, and administrative operations.</p><div class="login-features"><span>Role-based access</span><span>Independent review</span><span>Audit history</span></div></div><div class="login-story-footer">MONEYBAGS &nbsp; / &nbsp; AUTHORIZED ACCESS</div></section><section class="login-form-side"><div class="login-card"><p class="eyebrow">MONEYBAGS</p><h2>Sign in</h2><p>Enter your credentials to access the banking workspace.</p><form id="login-form"><label class="field">Username<input name="username" autocomplete="username" required maxlength="120" placeholder="Enter your username"></label><label class="field">Password<input name="password" type="password" autocomplete="current-password" required maxlength="72" placeholder="Enter your password"></label><label class="field">Authenticator code <span class="muted">Optional unless MFA is enabled</span><input name="otp" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" placeholder="Six-digit code"></label><p class="form-error" role="alert">${esc(message)}</p><button class="btn primary" type="submit">Sign in</button></form><div class="login-note">Use your issued credentials. Contact your administrator if you need access.</div><button class="btn signup-link" id="signup-link" type="button" hidden>Create a customer account</button></div></section></main>`;
  document.querySelector('#login-form').onsubmit=async event=>{
    event.preventDefault();if(!await validateJet(event.target))return;const button=event.target.querySelector('button');button.disabled=true;
    const values=new FormData(event.target);try{await login(values.get('username').trim(),values.get('password'),values.get('otp'));await start();}catch(error){event.target.querySelector('.form-error').textContent=errorText(error);}finally{button.disabled=false;}
  };
  api('/auth/signup-availability').then(value=>{const link=document.querySelector('#signup-link');if(link&&value.enabled){link.hidden=false;link.onclick=showSignup;}}).catch(()=>{});
  enhanceForms(root).catch(error=>toast(errorText(error),true));
}
function showSignup(){
  const card=document.querySelector('.login-card');if(!card)return;
  card.innerHTML=`<p class="eyebrow">MONEYBAGS</p><h2>Create a customer account</h2><p>Enter your details to join the demo workspace. KYC is treated as verified for this sign-up flow. Customers under 18 need guardian-assisted onboarding.</p><form id="signup-form"><label class="field">Legal name<input name="legalName" autocomplete="name" required maxlength="300"></label><label class="field">Date of birth<input name="dateOfBirth" type="date" required></label><label class="field">Username<input name="username" autocomplete="username" required minlength="3" maxlength="120" pattern="[A-Za-z0-9._@-]+"></label><label class="field">Password<input name="password" type="password" autocomplete="new-password" required minlength="10" maxlength="72"></label><label class="field">Confirm password<input name="confirmPassword" type="password" autocomplete="new-password" required minlength="10" maxlength="72"></label><p class="form-error" role="alert"></p><button class="btn primary" type="submit">Create account</button></form><button class="btn signup-link" id="back-to-login" type="button">Back to sign in</button>`;
  document.querySelector('#back-to-login').onclick=()=>signIn();
  document.querySelector('#signup-form').onsubmit=async event=>{
    event.preventDefault();if(!await validateJet(event.target))return;
    const form=event.target,values=new FormData(form),error=form.querySelector('.form-error'),button=form.querySelector('button');
    if(values.get('password')!==values.get('confirmPassword')){error.textContent='Passwords do not match.';return;}
    button.disabled=true;error.textContent='';
    try{await api('/auth/signup',{method:'POST',body:{username:values.get('username').trim(),legalName:values.get('legalName').trim(),dateOfBirth:values.get('dateOfBirth'),password:values.get('password')}});await login(values.get('username').trim(),values.get('password'));await start();}
    catch(failure){error.textContent=errorText(failure);button.disabled=false;}
  };
  enhanceForms(card).catch(error=>toast(errorText(error),true));
}
function shell(){
  const user=getSession().user;
  const known=state.menus.filter(m=>titles[m.routePath.slice(1)]);
  let nav=known.length?known.map(m=>({page:m.routePath.slice(1),label:m.labelKey})):Object.entries(titles).filter(([p])=>p==='security'||(p==='audit'?can('IAM_AUDIT_READ'):can('IAM_USER_READ'))).map(([page,label])=>({page,label}));
  if(!nav.some(n=>n.page==='security'))nav.push({page:'security',label:'My security'});
  if(user.userType!=='CUSTOMER'&&can('CIF_READ')&&!nav.some(n=>n.page==='customers'))nav.push({page:'customers',label:'Customers & KYC'});
  if(can('PRODUCT_READ')&&!nav.some(n=>n.page==='products'))nav.push({page:'products',label:'Product master'});
  nav=nav.filter(n=>n.page!=='assistant'&&(user.userType!=='CUSTOMER'||n.page!=='treasury'));
  for(const [page,config] of Object.entries(bankingPages))if((page==='treasury'?user.userType!=='CUSTOMER':page==='customerAccess'||!config.permission||can(config.permission))&&!nav.some(n=>n.page===page))nav.push({page,label:config.title});
  const navigationOrder=['banking','accounts','transactions','customerAccess','payments','beneficiaries','teller','loans','treasury','statements','currency','customers','products','privacy','dashboard','users','roles','access','audit','security'];
  nav.sort((a,b)=>navigationOrder.indexOf(a.page)-navigationOrder.indexOf(b.page));
  if(!nav.some(n=>n.page===state.page))state.page=nav[0]?.page||'security';
  const navigationSections=[
    ['Banking',['banking','accounts','transactions','customerAccess','payments','beneficiaries','teller','loans','treasury','statements','currency']],
    ['Customers and products',['customers','products','privacy']],
    ['Administration',['dashboard','users','roles','access','audit','security']]
  ];
  const navHtml=navigationSections.map(([section,pages])=>{
    const entries=nav.filter(n=>pages.includes(n.page));
    return entries.length?`<div class="nav-section"><p class="nav-heading">${section}</p>${entries.map(n=>`<button data-action="nav" data-id="${esc(n.page)}" class="${state.page===n.page?'active':''}" ${state.page===n.page?'aria-current="page"':''}><span>${esc(user.userType==='CUSTOMER'&&n.page==='products'?'Available products':titles[n.page]||n.label)}</span></button>`).join('')}</div>`:'';
  }).join('');
  root.innerHTML=`<div class="layout"><aside class="sidebar"><div class="logo"><img src="/favicon.svg" alt="">Moneybags</div><p class="eyebrow">BANKING WORKSPACE</p><nav class="nav" aria-label="Main navigation">${navHtml}</nav><div class="sidebar-foot"><strong>Moneybags</strong><br>Integrated banking workspace</div></aside><main class="main"><header class="topbar"><div class="breadcrumb">Workspace &nbsp; / &nbsp; <strong id="crumb">${esc(user.userType==='CUSTOMER'&&state.page==='products'?'Available products':titles[state.page])}</strong></div><div class="identity"><span class="avatar">${esc(user.username.slice(0,2).toUpperCase())}</span><div><div class="identity-name">${esc(user.username)}</div><div class="identity-role">${esc(user.userType)} · ${esc(user.roles[0]||'No role assigned')}</div></div>${action('Sign out','logout','','btn small')}</div></header><div class="content" id="content"></div></main></div>${assistantWidget()}`;
  bindAssistant();
}
async function start(){
  if(!getSession()){signIn();return;}
  try{const user=await api('/auth/me');saveSession({...getSession(),user});state.menus=await api('/iam/menus');if(!can('IAM_USER_READ')&&state.page==='dashboard')state.page='banking';shell();await render();}
  catch(error){if(!getSession())signIn(error.message);else{shell();document.querySelector('#content').innerHTML=`<div class="panel error-panel">${esc(errorText(error))}${action('Try again','retry')}</div>`;}}
}
async function catalog(){
  const [users,roles,permissions]=await Promise.all([api('/iam/users?size=100'),api('/iam/roles'),api('/iam/permissions')]);state.users=users.items;state.roles=roles;state.permissions=permissions;
}
async function render(){
  if(!getSession())return;
  const serial=++state.render;const content=document.querySelector('#content');if(!content)return;
  await disposeJet(content);
  document.querySelectorAll('.nav button').forEach(b=>{const active=b.dataset.id===state.page;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});document.querySelector('#crumb').textContent=getSession().user.userType==='CUSTOMER'&&state.page==='products'?'Available products':titles[state.page];
  content.innerHTML='<div class="loading">Loading your workspace…</div>';
  try{let html;if(bankingPages[state.page])html=await bankingScreen(state.page);else switch(state.page){case'dashboard':html=await overview();break;case'users':html=await users();break;case'roles':html=await roles();break;case'access':html=await access();break;case'audit':html=await audit();break;case'customers':html=await customersScreen();break;case'products':html=await productsScreen();break;default:html=await security();}if(serial!==state.render||!getSession())return;await disposeJet(content);content.innerHTML=html;bindForms();bindDomainForms();bindBankingForms();await enhanceForms(content);}
  catch(error){if(serial!==state.render||!getSession())return;content.innerHTML=`<section class="panel"><div class="error-panel">${esc(errorText(error))}</div><div class="panel-body">${action('Retry','reload')}</div></section>`;}
}
async function overview(){
  const [d,requests]=await Promise.all([api('/iam/dashboard'),api('/iam/access-requests'),catalog()]);state.requests=requests;
  return head('Identity and access','Monitor identities, roles, access requests, and sessions.',can('IAM_USER_CREATE')?action('Create user','new-user','','btn primary'):'')+
    (d.checkerSetupAvailable&&can('IAM_ACCESS_APPROVE')?`<div class="notice"><strong>Set up your independent checker</strong>Access requests need a different approver. Create the second administrator once to get started. Every later role assignment uses the approval workflow.<br>${action('Set up checker','new-checker','','btn')}</div>`:'')+
    `<h2 class="section-heading">Current position</h2><div class="stats">${[['Total identities',d.users,`${d.activeUsers} active`],['Roles',d.roles,'Active role definitions'],['Awaiting review',d.pendingRequests,'Access decisions pending'],['Active sessions',d.activeSessions,'Current user sessions']].map(s=>`<div class="stat"><div class="stat-title">${esc(s[0])}</div><div class="stat-value">${esc(s[1])}</div><div class="stat-note">${esc(s[2])}</div></div>`).join('')}</div>`+
    `<div class="split">${panel('Recent access requests',requestTable(requests.slice(0,5)),action('View all','nav','access','btn small'))}${panel('Administrative areas',`<div class="panel-body admin-links">${[['User directory','users'],['Roles and permissions','roles'],['Access requests','access'],['Audit trail','audit']].map(([title,page])=>action(title,'nav',page,'btn')).join('')}</div>`)}</div>`;
}
async function users(){
  const value=await api(`/iam/users?page=${state.userPage}&size=15&search=${encodeURIComponent(state.search)}&status=${encodeURIComponent(state.status)}`);state.users=value.items;
  return head('Users','Create and manage employees, customers, and service users.',can('IAM_USER_CREATE')?action('Create user','new-user','','btn primary'):'')+
    panel('User directory',`<form id="user-search" class="toolbar">${field('Search username','search','search',{required:false,value:state.search,placeholder:'Search identities…',maxlength:120})}${select('Status','status',[{value:'',label:'All statuses'},'PENDING_ACTIVATION','ACTIVE','AUTH_LOCKED','SUSPENDED','DISABLED','CLOSED'],state.status,false)}<button class="btn" type="submit">Search</button></form>`+
      table(['Username','Type','Status','Employee reference','Created','Action'],value.items.map(u=>[`<strong>${esc(u.username)}</strong>`,esc(u.userType),badge(u.status),esc(u.employeeRef||'—'),esc(date(u.createdAt)),action('View user','user-detail',u.userId)]),'No users match your filters.')+
      `<div class="pagination"><span>${value.total} identities · Page ${value.page+1}</span><div><button class="btn small" data-action="user-prev" ${value.page===0?'disabled':''}>Previous</button><button class="btn small" data-action="user-next" ${(value.page+1)*value.size>=value.total?'disabled':''}>Next</button></div></div>`);
}
async function newUser(checker=false){
  const demoSignup=!checker&&(await api('/auth/signup-availability')).enabled;
  const inputs=`<p class="hint">${checker?'This creates the second active administrator as a one-time setup exception. Keep its credentials separate from the first administrator.':demoSignup?'Demo customers become active with a verified CIF and can open an eligible account. Employee and service identities begin pending activation.':'New identities begin pending activation. Activate the identity, then submit an access request to assign a role.'}</p><div class="grid2">${field('Username','username','text',{maxlength:120,minlength:3})}${checker?'':select('User type','userType',['EMPLOYEE','CUSTOMER','SERVICE'])}${field('Employee reference','employeeRef','text',{required:checker,maxlength:80,placeholder:'Required for employees'})}${field('Initial password','password','password',{minlength:10,maxlength:72})}</div>${demoSignup?`<div id="demo-customer-fields" hidden><div class="grid2">${field('Legal name','legalName','text',{maxlength:300,required:false})}${field('Date of birth','dateOfBirth','date',{required:false})}</div></div>`:''}<p class="hint">Passwords need at least 10 characters and at most 72 UTF-8 bytes. Share the initial password privately.</p>`;
  dialog(checker?'Set up independent checker':'Create digital identity',inputs,async data=>{
    if(demoSignup&&data.get('userType')==='CUSTOMER'){
      const created=await api('/iam/users/demo-customer',{method:'POST',body:{username:data.get('username'),legalName:data.get('legalName'),dateOfBirth:data.get('dateOfBirth'),password:data.get('password')}});
      await render();dialog('Customer ready to sign in',`<p class="notice">The customer is active with verified demo KYC. They can sign in and open an eligible account.</p><dl class="details">${detail('Username',created.username)}${detail('CIF ID',created.cifId)}</dl>`);return false;
    }
    const created=await api(checker?'/iam/setup/checker':'/customer-access/users',{method:'POST',body:{username:data.get('username'),userType:checker?'EMPLOYEE':data.get('userType'),employeeRef:data.get('employeeRef')||null,password:data.get('password')}});if(created.customerHash){await render();dialog('Save the account-holder access key',`<p class="notice">Store this securely. It is shown only now and may be needed for authorized bank officers to view financial details. Customers can view their own accounts after signing in.</p><code>${esc(created.customerHash)}</code>`);return false;}toast(checker?'Checker created. Sign in separately to review access requests.':'Identity created. Activate it before granting access.');await render();
  });
  const type=document.querySelector('#dialog [name=userType]');if(type){const update=()=>{const e=document.querySelector('#dialog [name=employeeRef]');e.required=type.value==='EMPLOYEE';e.disabled=!e.required;if(e.disabled)e.value='';const employeeComponent=e.closest('label').querySelector('oj-input-text');if(employeeComponent){employeeComponent.required=e.required;employeeComponent.disabled=e.disabled;}const group=document.querySelector('#demo-customer-fields');if(group){group.hidden=type.value!=='CUSTOMER';for(const input of group.querySelectorAll('input')){input.required=!group.hidden;input.disabled=group.hidden;if(group.hidden)input.value='';}for(const component of group.querySelectorAll('oj-input-text,oj-input-date')){component.required=!group.hidden;component.disabled=group.hidden;}}};type.onchange=update;update();}
}
async function userDetail(id){
  const [d,roles]=await Promise.all([api(`/iam/users/${id}`),api('/iam/roles')]);state.detail=d;state.roles=roles;
  const u=d.user;dialog(u.username,`<dl class="details">${detail('User ID',u.userId)}${detail('User type',u.userType)}${detail('Status',u.status)}${detail('Employee reference',u.employeeRef)}${detail('Created',date(u.createdAt))}${detail('Entitlement version',u.entitlementVersion)}</dl>`+
    (can('IAM_USER_MANAGE')?`<div class="menu-tools">${action('Change status','user-status',id)}${action('Reset password','user-reset',id)}${u.userId!==getSession().user.userId?action('Reset lost MFA','admin-mfa-reset',id):''}${u.userType==='CUSTOMER'?action('Link existing CIF','new-link',id):''}</div>`:'')+
    `<h3 class="section-label">Role assignments</h3>`+table(['Role / scope','Validity','Status',''],d.assignments.map(a=>[`${esc(roleName(a.roleId))}<span class="sub">${esc(a.scopeType)} ${esc(a.scopeRef||'')} · ${esc(d.dimensions.filter(x=>x.assignmentId===a.assignmentId).map(x=>x.dimensionCode+': '+x.scopeValue).join(', '))}</span>`,`${esc(date(a.validFrom))}<span class="sub">Until ${esc(date(a.validTo))}</span>`,badge(a.status),a.status==='ACTIVE'&&can('IAM_ACCESS_MANAGE')?action('Request revoke','request-revoke',a.assignmentId):'']))+
    (can('IAM_ACCESS_MANAGE')?`<div class="menu-tools">${action('Request new access','new-access-user',id)}</div>`:'')+
    `<h3 class="section-label">Customer links</h3>`+table(['CIF','Relationship','Status',''],d.links.map(l=>[esc(l.cifId),esc(l.relationshipType),badge(l.status),l.status==='ACTIVE'&&can('IAM_USER_MANAGE')?action('Revoke link','revoke-link',l.linkId,'btn small danger'):'']))+
    `<h3 class="section-label">Sessions</h3>`+sessionTable(d.sessions,true,id),null);
}
function statusDialog(){const u=state.detail.user;const next={PENDING_ACTIVATION:['ACTIVE','DISABLED','CLOSED'],ACTIVE:['SUSPENDED','DISABLED','AUTH_LOCKED','CLOSED'],AUTH_LOCKED:['ACTIVE','SUSPENDED','DISABLED','CLOSED'],SUSPENDED:['ACTIVE','DISABLED','CLOSED'],DISABLED:['ACTIVE','CLOSED'],CLOSED:[]}[u.status];if(!next.length){toast('Closed identities cannot be reactivated.',true);return;}
  dialog(`Change status · ${u.username}`,`<p class="hint">Current status: ${esc(u.status)}. Deactivation ends all active sessions. Status changes preserve banking and identity history.</p>${select('New status','status',next)}${reason()}`,async data=>{await api(`/iam/users/${u.userId}/status`,{method:'PATCH',body:{rowVersion:u.rowVersion,status:data.get('status'),reason:data.get('reason')}});toast('User status updated.');await render();});
}
function resetDialog(){const u=state.detail.user;dialog(`Reset password · ${u.username}`,`${field('New password','password','password',{minlength:10,maxlength:72})}${reason()}<p class="hint">This ends all existing sessions. It does not reactivate a suspended or disabled user.</p>`,async data=>{await api(`/iam/users/${u.userId}/password-reset`,{method:'POST',body:Object.fromEntries(data)});toast('Password reset. All existing sessions ended.');if(u.userId===getSession()?.user.userId){saveSession(null);signIn('Password reset. Sign in with your new password.');}else await render();});}
function newLink(){const u=state.detail.user;dialog(`Link CIF · ${u.username}`,`<p class="hint">The CIF must already exist and be active in module 2. A customer link does not grant account operating authority.</p>${field('Existing CIF ID','cifId','text',{maxlength:36})}${field('Relationship type','relationshipType','text',{maxlength:24,value:'SELF'})}`,async data=>{await api(`/iam/users/${u.userId}/customer-links`,{method:'POST',body:Object.fromEntries(data)});toast('Customer link created.');await render();});}
async function roles(){await catalog();return head('Roles & permissions','Group responsibilities, define permission sets, and configure authority limits.',can('IAM_ROLE_MANAGE')?action('+ New role','new-role','','btn primary'):'')+
  panel('Role catalogue',table(['Role','Sensitivity','Status','Actions'],state.roles.map(r=>[`<strong>${esc(r.displayName)}</strong><span class="sub">${esc(r.roleCode)}</span>`,r.sensitiveFlag==='Y'?badge('SENSITIVE'):'Standard',badge(r.status),action('View role','role-detail',r.roleId)])))+
  panel('Permission catalogue',table(['Permission','Resource','Action','Step-up'],state.permissions.map(p=>[esc(p.permissionCode),esc(p.resourceCode),esc(p.actionCode),p.stepUpRequired==='Y'?badge('MFA REQUIRED'):'Not required'])),can('IAM_ROLE_MANAGE')?action('+ New permission','new-permission','','btn small'):'');}
function permissionChecks(selected=[]){return `<p class="section-label">Permissions</p><div class="checklist">${state.permissions.map(p=>`<label><input type="checkbox" name="permissionIds" value="${esc(p.permissionId)}" ${selected.includes(p.permissionId)?'checked':''}>${esc(p.permissionCode)}</label>`).join('')}</div>`;}
function roleDialog(edit=false){const d=state.roleDetail,r=d?.role;dialog(edit?`Edit role · ${r.displayName}`:'Create role',`<div class="grid2">${edit?'':field('Role code','roleCode','text',{maxlength:80,placeholder:'BRANCH_OFFICER'})}${field('Display name','displayName','text',{maxlength:120,value:edit?r.displayName:''})}${select('Sensitivity','sensitive',[{value:'false',label:'Standard'},{value:'true',label:'Sensitive'}],edit&&r.sensitiveFlag==='Y'?'true':'false')}${edit?select('Status','status',['ACTIVE','RETIRED'],r.status):''}</div>${permissionChecks(edit?d.permissions.map(p=>p.permissionId):[])}<p class="hint">Changing role permissions affects all active assignments. Retiring a role removes its permissions from subsequent requests.</p>`,async data=>{const body={displayName:data.get('displayName'),sensitive:data.get('sensitive')==='true',permissionIds:data.getAll('permissionIds')};if(edit){body.rowVersion=r.rowVersion;body.status=data.get('status');}else body.roleCode=data.get('roleCode');await api(edit?`/iam/roles/${r.roleId}`:'/iam/roles',{method:edit?'PUT':'POST',body});toast('Role saved.');await render();});}
async function roleDetail(id){if(!state.permissions.length)await catalog();const d=await api(`/iam/roles/${id}`);state.roleDetail=d;const r=d.role;dialog(r.displayName,`<dl class="details">${detail('Role code',r.roleCode)}${detail('Status',r.status)}${detail('Sensitive role',r.sensitiveFlag==='Y'?'Yes':'No')}${detail('Version',r.rowVersion)}</dl><div>${tags(d.permissions.map(p=>p.permissionCode))}</div><h3 class="section-label">Approval authority</h3>`+table(['Authority','Currency / limit','Validity',''],d.authorities.map(a=>[esc(a.authorityCode),`<span class="amount-value">${esc(formatAmount(a.maxAmount,a.currencyCode==='*'?'':a.currencyCode))}</span><span class="sub">${a.currencyCode==='*'?'All currencies · ':''}Maximum rate: ${a.maxRatePct==null?'—':esc(formatDecimal(a.maxRatePct))+'%'}</span>`,`${esc(date(a.validFrom))}<span class="sub">Until ${esc(date(a.validTo))}</span>`,can('IAM_ROLE_MANAGE')?action('End','end-authority',a.authorityId,'btn small danger'):'']))+
  (can('IAM_ROLE_MANAGE')?`<div class="menu-tools">${r.roleCode==='BANK_ADMIN'?'<p class="hint">The initial administrator role is protected from editing.</p>':action('Edit role','edit-role',id)}${action('Add authority','new-authority',id)}</div>`:''),null);}
function newPermission(){dialog('Create permission',`<div class="grid2">${field('Permission code','permissionCode','text',{maxlength:100,placeholder:'LOAN_APPROVE'})}${field('Resource code','resourceCode','text',{maxlength:60,placeholder:'LOAN'})}${field('Action code','actionCode','text',{maxlength:60,placeholder:'APPROVE'})}${select('Require fresh MFA','stepUpRequired',[{value:'false',label:'No'},{value:'true',label:'Yes'}])}</div>`,async data=>{await api('/iam/permissions',{method:'POST',body:{...Object.fromEntries(data),stepUpRequired:data.get('stepUpRequired')==='true'}});toast('Permission created. Add it to a role to grant access.');await render();});}
function newAuthority(){const r=state.roleDetail.role;dialog(`Add authority · ${r.displayName}`,`<div class="grid2">${field('Authority code','authorityCode','text',{maxlength:80,placeholder:'LOAN_APPROVE'})}${field('Currency code','currencyCode','text',{maxlength:3,value:'INR'})}${field('Maximum amount','maxAmount','number',{required:false,min:0,step:'0.0001'})}${field('Maximum rate %','maxRatePct','number',{required:false,min:0,step:'0.00000001'})}${field('Valid from','validFrom','datetime-local',{value:localDate()})}${field('Valid until (optional)','validTo','datetime-local',{required:false})}</div><p class="hint">Provide at least one limit. Use * for all currencies. Amounts are evaluated on the same scoped assignment as the permission.</p>`,async data=>{await api(`/iam/roles/${r.roleId}/authorities`,{method:'POST',body:{authorityCode:data.get('authorityCode'),currencyCode:data.get('currencyCode'),maxAmount:data.get('maxAmount')||null,maxRatePct:data.get('maxRatePct')||null,validFrom:iso(data.get('validFrom')),validTo:iso(data.get('validTo'))}});toast('Approval authority added.');await render();});}
function requestTable(items){return table(['Change / role','Target identity','Scope','Status',''],items.map(r=>[`${badge(r.changeType)}<span class="sub">${esc(roleName(r.roleId))}</span>`,esc(userName(r.targetUserId)),`${esc(r.scopeType)}<span class="sub">${esc(r.scopeRef||'Across permitted resources')}</span>`,badge(r.status),action('Review details','request-detail',r.requestId)]),'No access requests yet.');}
async function access(){await catalog();state.requests=await api('/iam/access-requests');return head('Access requests','Grant or revoke access through independent maker–checker review.',can('IAM_ACCESS_MANAGE')?action('+ Request access','new-access','','btn primary'):'')+`<div class="notice"><strong>Every change needs a second person</strong>The maker and checker must be different users. A checker also cannot approve a change to their own access. Open a request to review its role, scope, dimensions, and validity.</div>`+panel('Request queue · latest 200',requestTable(state.requests));}
async function accessDialog(userId='',assignment=null){
  const detail=state.detail;await catalog();
  if(assignment){const dimensions=detail.dimensions.filter(d=>d.assignmentId===assignment.assignmentId).map(d=>({dimensionCode:d.dimensionCode,scopeValue:d.scopeValue}));dialog('Request access revocation',`<dl class="details">${detailHtml(assignment)}</dl>${reason()}<p class="hint">A different administrator must approve this revocation. Access stays effective until approval.</p>`,async data=>{await api('/iam/access-requests',{method:'POST',body:{targetUserId:assignment.userId,roleId:assignment.roleId,changeType:'REVOKE',targetAssignmentId:assignment.assignmentId,scopeType:assignment.scopeType,scopeRef:assignment.scopeRef,validFrom:assignment.validFrom,validTo:assignment.validTo,reason:data.get('reason'),dimensions}});toast('Revocation submitted for independent review.');state.page='access';await render();});return;}
  dialog('Request new access',`<div class="grid2">${select('Target user','targetUserId',[{value:'',label:'Select a user'},...state.users.filter(u=>u.status==='ACTIVE').map(u=>({value:u.userId,label:`${u.username} · ${u.userType}`}))],userId)}${select('Role','roleId',[{value:'',label:'Select a role'},...state.roles.filter(r=>r.status==='ACTIVE').map(r=>({value:r.roleId,label:r.displayName}))])}${select('Primary scope','scopeType',['GLOBAL','BRANCH','REGION','SELF'])}${field('Scope reference','scopeRef','text',{required:false,maxlength:80,placeholder:'Branch or region reference'})}${field('Valid from','validFrom','datetime-local',{value:localDate()})}${field('Valid until (optional)','validTo','datetime-local',{required:false})}${field('Product types (comma separated)','productTypes','text',{required:false,placeholder:'SAVINGS, CURRENT'})}${field('Currencies (comma separated)','currencies','text',{required:false,placeholder:'INR, USD'})}${reason()}</div><p class="hint">Same-dimension values are alternatives. Different dimensions must all match. Only active users and roles are listed.</p>`,async data=>{const dimensions=[...String(data.get('productTypes')).split(',').map(v=>({dimensionCode:'PRODUCT_TYPE',scopeValue:v.trim().toUpperCase()})),...String(data.get('currencies')).split(',').map(v=>({dimensionCode:'CURRENCY',scopeValue:v.trim().toUpperCase()}))].filter(d=>d.scopeValue);await api('/iam/access-requests',{method:'POST',body:{targetUserId:data.get('targetUserId'),roleId:data.get('roleId'),changeType:'GRANT',scopeType:data.get('scopeType'),scopeRef:data.get('scopeRef')||null,validFrom:iso(data.get('validFrom')),validTo:iso(data.get('validTo')),reason:data.get('reason'),dimensions}});toast('Access request submitted. A different user must review it.');state.page='access';await render();});
  const scope=document.querySelector('#dialog [name=scopeType]');const update=()=>{const ref=document.querySelector('#dialog [name=scopeRef]');ref.required=['BRANCH','REGION'].includes(scope.value);ref.disabled=!ref.required;if(ref.disabled)ref.value='';};scope.onchange=update;update();
}
function detailHtml(r){return detail('Role',roleName(r.roleId))+detail('User',userName(r.userId||r.targetUserId))+detail('Scope',`${r.scopeType} ${r.scopeRef||''}`)+detail('Valid from',date(r.validFrom))+detail('Valid until',date(r.validTo));}
async function requestDetail(id){
  if(!state.roles.length)await catalog();const d=await api(`/iam/access-requests/${id}`);state.requestDetail=d;const r=d.request;
  const canDecide=r.status==='SUBMITTED'&&can('IAM_ACCESS_APPROVE')&&r.makerUserId!==getSession().user.userId&&r.targetUserId!==getSession().user.userId;
  dialog('Review access request',`<dl class="details">${detail('Change',r.changeType)}${detail('Status',r.status)}${detailHtml(r)}${detail('Maker',userName(r.makerUserId))}${detail('Checker',r.checkerUserId?userName(r.checkerUserId):'Awaiting review')}${detail('Submitted',date(r.createdAt))}${detail('Decision time',date(r.decidedAt))}</dl><h3 class="section-label">Scope dimensions</h3>${tags(d.dimensions.map(x=>x.dimensionCode+': '+x.scopeValue))}<h3 class="section-label">Business reason</h3><p class="hint">${esc(r.reason)}</p>`+
    (canDecide?`<div class="menu-tools">${action('Approve request','approve',r.requestId,'btn primary')}${action('Reject request','reject',r.requestId,'btn danger')}</div>`:r.status==='SUBMITTED'?'<div class="notice">A different authorized user must decide this request. Makers and targets cannot approve their own access changes.</div>':''),null);
}
async function audit(){const [events,outbox]=await Promise.all([api('/iam/audit'),api('/iam/outbox')]);return head('Audit trail','Trace security decisions and changes across your workspace.')+panel('Security events · latest 200',`<form id="audit-search" class="toolbar">${field('Event type or resource ID','search','search',{required:false,maxlength:120,placeholder:'ACCESS_REQUEST, PASSWORD, LOGIN…'})}<button class="btn" type="submit">Search</button></form><div id="audit-table">${auditTable(events)}</div>`)+panel('Stored domain events · latest 100',table(['Event','Resource','Recorded','Delivery'],outbox.map(e=>[esc(e.eventType),`${esc(e.aggregateType)}<span class="sub">${esc(e.aggregateId)}</span>`,esc(date(e.occurredAt)),e.publishedAt?badge('PUBLISHED'):badge('STORED')])));}
function auditTable(events){return table(['Event / reference','Actor','Resource','Result','Time'],events.map(e=>[`<strong>${esc(e.eventType)}</strong><span class="sub">${esc(e.correlationId)}</span>`,esc(e.actorUserId?userName(e.actorUserId):'Anonymous'),`${esc(e.resourceType||'—')}<span class="sub">${esc(e.resourceId||'—')}</span>`,badge(e.result),esc(date(e.occurredAt))]));}
function sessionTable(sessions,admin=false,userId=''){return table(['Device / client','Last active','Expiry / status',''],sessions.map(s=>[`${esc(s.deviceRef||'Browser').slice(0,85)}<span class="sub">${esc(s.clientId)} ${s.current?'· This session':''}</span>`,esc(date(s.lastActivityAt)),`${badge(s.status)}<span class="sub">Idle: ${esc(date(s.idleExpiresAt))}</span>`,s.status==='ACTIVE'&&(admin?can('IAM_USER_MANAGE'):true)?`<button class="btn small danger" data-action="${admin?'admin-session':'own-session'}" data-id="${esc(s.sessionId)}" data-user="${esc(userId)}">Revoke</button>`:'']));}
async function security(){
  const [sessions,factors,user]=await Promise.all([api('/auth/sessions'),api('/iam/factors'),api('/auth/me')]);if(!getSession())return '';saveSession({...getSession(),user});state.factors=factors;const enabled=factors.some(f=>f.status==='ACTIVE');
  return head('My security','Manage your password, authenticator, and signed-in devices.')+`<div class="security-grid">`+
    panel('Your identity',`<div class="panel-body"><dl class="details">${detail('Username',user.username)}${detail('User type',user.userType)}${detail('Active roles',user.roles.join(', ')||'No assigned role')}${detail('Linked CIFs',user.cifIds.join(', ')||'No linked CIF')}</dl><p class="section-label">Current permissions</p>${tags(user.permissions)}<p class="hint">Permissions are reloaded from Oracle on every authenticated request.</p>${action('Refresh session','refresh-session')}</div>`)+
    panel('Authenticator',`<div class="panel-body"><p>${enabled?badge('ACTIVE'):'Not enabled'}</p><p class="hint">Use a TOTP authenticator app. Your six-digit code is required at sign-in after enrollment. Fresh step-up is valid for five minutes.</p>${enabled?`${action('Verify step-up','step-up')}${factors.filter(f=>f.status==='ACTIVE').map(f=>action('Remove authenticator','revoke-factor',f.factorId,'btn danger')).join('')}`:action('Set up authenticator','enroll-factor','','btn primary')}</div>`)+
    panel('Change password',`<form id="password-form" class="panel-body">${field('Current password','currentPassword','password')}${field('New password','newPassword','password',{minlength:10,maxlength:72})}<p class="hint">Changing your password ends every existing session, including this one.</p><p class="form-error" role="alert"></p><button class="btn primary" type="submit">Change password</button></form>`)+
    panel('Check my authorization',`<form id="authorization-form" class="panel-body"><p class="hint">Try a permission against an exact branch, product, currency, and authority limit. This checks your current identity; it does not perform a financial operation.</p>${field('Permission code','permissionCode','text',{value:user.permissions[0]||'',maxlength:100})}<div class="grid2">${field('Branch reference','branchRef','text',{required:false,maxlength:80})}${field('Region reference','regionRef','text',{required:false,maxlength:80})}${field('CIF ID (SELF scope)','cifId','text',{required:false,maxlength:36})}${field('Product type','productType','text',{required:false,maxlength:80})}${field('Currency code','currencyCode','text',{required:false,maxlength:3,value:'INR'})}${field('Authority code','authorityCode','text',{required:false,maxlength:80})}${field('Amount','amount','number',{required:false,min:0,step:'0.0001'})}${field('Rate %','ratePct','number',{required:false,min:0,step:'0.00000001'})}</div><p class="form-error" role="alert"></p><button class="btn" type="submit">Check authorization</button><p id="authorization-result" class="hint"></p></form>`)+
    `<section class="panel wide"><div class="panel-heading"><h3>Your sessions</h3></div>${sessionTable(sessions)}</section></div>`+
    (can('IAM_ROLE_MANAGE')?panel('Workspace navigation',`<div class="panel-body"><p class="hint">Menus control navigation visibility. Backend permissions still protect every operation.</p>${action('Manage menus','manage-menus')}</div>`):'');
}
async function enrollFactor(){const enrollment=await api('/iam/factors/totp',{method:'POST'});dialog('Set up your authenticator',`<p class="hint">In your authenticator app, add a time-based account named Moneybags using this secret. It is shown only during enrollment.</p><p class="code">${esc(enrollment.secret)}</p><p class="hint">Or use the provisioning URI in an authenticator that accepts it:</p><p class="code">${esc(enrollment.otpauthUri)}</p>${field('Authenticator code','code','text',{maxlength:6,minlength:6,placeholder:'Six digits from your app'})}<p class="hint">After verification, sign-ins require MFA. Each code can be used once; wait for the next code before signing in again.</p>`,async data=>{await api(`/iam/factors/${enrollment.factorId}/confirm`,{method:'POST',body:{code:data.get('code')}});toast('Authenticator enabled. Keep the original runtime/mfa.key file.');await render();});}
function stepUp(){dialog('Verify fresh MFA',field('Authenticator code','code','text',{maxlength:6,minlength:6}),async data=>{await api('/iam/step-up',{method:'POST',body:{code:data.get('code')}});toast('MFA verified for five minutes.');await render();});}
function revokeFactor(id){dialog('Remove authenticator',`${field('Your password','password','password')}${field('Current authenticator code','code','text',{maxlength:6,minlength:6})}<p class="hint">Use a fresh unused code. Future sign-ins will use your password.</p>`,async data=>{await api(`/iam/factors/${id}/revoke`,{method:'POST',body:Object.fromEntries(data)});toast('Authenticator removed.');await render();});}
async function manageMenus(){if(!state.permissions.length)await catalog();state.allMenus=await api('/iam/menus?all=true');dialog('Workspace menus',table(['Label','Route','Status',''],state.allMenus.map(m=>[esc(m.labelKey),esc(m.routePath),badge(m.status),action('Edit','edit-menu',m.menuId)]))+`<p class="hint">This college frontend supports /dashboard, /users, /roles, /access, /audit, and /security.</p>${action('Add menu','new-menu')}`,null);}
function menuDialog(id){const m=state.allMenus?.find(x=>x.menuId===id);dialog(m?'Edit menu':'Add menu',`<div class="grid2">${field('Label','labelKey','text',{value:m?.labelKey,maxlength:120})}${select('Route','routePath',Object.keys(titles).map(p=>({value:'/'+p,label:titles[p]})),m?.routePath||'/dashboard')}${field('Sort order','sortOrder','number',{value:m?.sortOrder??0,min:0})}${select('Status','status',['ACTIVE','HIDDEN'],m?.status||'ACTIVE')}${select('Required permission','requiredPermissionId',permissionOptions(),m?.requiredPermissionId||'',false)}</div>`,async data=>{await api(m?`/iam/menus/${m.menuId}`:'/iam/menus',{method:m?'PUT':'POST',body:{...Object.fromEntries(data),sortOrder:Number(data.get('sortOrder')),clientId:'MONEYBAGS_WEB',parentMenuId:null,requiredPermissionId:data.get('requiredPermissionId')||null}});toast('Menu saved.');state.menus=await api('/iam/menus');shell();await render();});}
function bindForms(){
  const search=document.querySelector('#user-search');if(search)search.onsubmit=async e=>{e.preventDefault();const d=new FormData(e.target);state.search=d.get('search');state.status=d.get('status');state.userPage=0;await render();};
  const audit=document.querySelector('#audit-search');if(audit)audit.onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const events=await api('/iam/audit?search='+encodeURIComponent(new FormData(e.target).get('search')));document.querySelector('#audit-table').innerHTML=auditTable(events);}catch(error){toast(errorText(error),true);}finally{b.disabled=false;}};
  const password=document.querySelector('#password-form');if(password)password.onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await api('/iam/password',{method:'POST',body:Object.fromEntries(new FormData(e.target))});saveSession(null);signIn('Password changed. Sign in with your new password.');}catch(error){e.target.querySelector('.form-error').textContent=errorText(error);}finally{b.disabled=false;}};
  const check=document.querySelector('#authorization-form');if(check)check.onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;e.target.querySelector('.form-error').textContent='';try{const data=Object.fromEntries(new FormData(e.target));for(const key of Object.keys(data))if(data[key]==='')data[key]=null;const result=await api('/iam/authorization/check',{method:'POST',body:data});const target=document.querySelector('#authorization-result');target.innerHTML=`${badge(result.allowed?'APPROVED':'DENIED')} ${esc(result.reason)}`;}catch(error){e.target.querySelector('.form-error').textContent=errorText(error);}finally{b.disabled=false;}};
}
document.addEventListener('click',async event=>{
  const button=event.target.closest('[data-action]');if(!button||button.disabled)return;const {action:type,id}=button.dataset;button.disabled=true;
  try{switch(type){
    case'nav':await router.go({path:id});break;
    case'reload':await render();break;case'retry':await start();break;
    case'logout':await logout();closeDialog();signIn();break;
    case'new-user':await newUser();break;case'new-checker':await newUser(true);break;
    case'user-prev':state.userPage--;await render();break;case'user-next':state.userPage++;await render();break;
    case'user-detail':await userDetail(id);break;case'user-status':statusDialog();break;case'user-reset':resetDialog();break;case'new-link':newLink();break;
    case'admin-mfa-reset':dialog('Reset lost authenticator',`${reason()}<p class="hint">This revokes the user's authenticator factors and ends all their sessions. They must sign in again and enroll a new authenticator.</p>`,async data=>{await api(`/iam/users/${id}/factor-reset`,{method:'POST',body:{reason:data.get('reason')}});toast('Authenticator reset; existing sessions ended.');await render();});break;
    case'revoke-link':dialog('Revoke customer link','<p class="hint">This ends the digital link to the CIF. The customer record and bank accounts remain available to authorized users.</p>',async()=>{await api(`/iam/users/${state.detail.user.userId}/customer-links/${id}`,{method:'DELETE'});toast('Customer link revoked.');await render();});break;
    case'new-role':if(!state.permissions.length)await catalog();roleDialog();break;case'edit-role':roleDialog(true);break;case'role-detail':await roleDetail(id);break;case'new-permission':newPermission();break;case'new-authority':newAuthority();break;
    case'end-authority':dialog('End approval authority','<p class="hint">This ends the selected limit immediately. Role permissions remain unchanged.</p>',async()=>{await api(`/iam/roles/${state.roleDetail.role.roleId}/authorities/${id}`,{method:'DELETE'});toast('Authority ended.');await render();});break;
    case'new-access':await accessDialog();break;case'new-access-user':await accessDialog(id);break;case'request-revoke':await accessDialog('',state.detail.assignments.find(a=>a.assignmentId===id));break;case'request-detail':await requestDetail(id);break;
    case'approve':case'reject':{const r=state.requestDetail.request;await api(`/iam/access-requests/${id}/decision`,{method:'POST',body:{rowVersion:r.rowVersion,decision:type==='approve'?'APPROVED':'REJECTED'}});closeDialog();toast(type==='approve'?'Access request approved.':'Access request rejected.');await render();break;}
    case'own-session':case'admin-session':{const current=id===getSession().accessToken;dialog('Revoke session',`<p class="hint">${current?'This will sign you out of the current session.':'This ends the selected device session immediately.'}</p>`,async()=>{await api(type==='own-session'?`/auth/sessions/${id}`:`/iam/users/${button.dataset.user}/sessions/${id}`,{method:'DELETE'});if(current){saveSession(null);signIn('Session revoked. Sign in again.');}else{toast('Session revoked.');await render();}});break;}
    case'refresh-session':await refresh();toast('Session refreshed; refresh token rotated.');await render();break;
    case'enroll-factor':await enrollFactor();break;case'step-up':stepUp();break;case'revoke-factor':revokeFactor(id);break;
    case'manage-menus':await manageMenus();break;case'new-menu':menuDialog();break;case'edit-menu':menuDialog(id);break;
  }}catch(error){toast(errorText(error),true);}finally{button.disabled=false;}
});
window.addEventListener('session-ended',()=>{state.render++;closeDialog();signIn('Your session ended. Please sign in again.');});
configureDomains(render);
configureBanking(render);
await start();

