-- Apply after the supplied Moneybags Modules 1-10 installer, in the same Oracle schema.
-- Stores revision intent separately because M10_STATEMENT_REQUEST has no prior-ID column.
CREATE TABLE M10_STATEMENT_REVISION_INTENT (
  REQUEST_ID VARCHAR2(36 CHAR) PRIMARY KEY
    REFERENCES M10_STATEMENT_REQUEST(REQUEST_ID),
  PRIOR_STATEMENT_ID VARCHAR2(36 CHAR) NOT NULL
    REFERENCES M10_STATEMENT_SNAPSHOT(STATEMENT_ID),
  CORRECTION_REASON_CODE VARCHAR2(80 CHAR) NOT NULL,
  CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
