-- Additive objects only; apply once to an existing Money Bags schema.
CREATE TABLE MBX_CUSTOMER_SECRET (
 USER_ID VARCHAR2(36 CHAR) PRIMARY KEY REFERENCES M01_IAM_USER(USER_ID),
 SECRET_DIGEST RAW(32) NOT NULL,
 CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 ROTATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE MBX_AUDIT (
 EVENT_ID VARCHAR2(36 CHAR) PRIMARY KEY,
 ACTOR_ID VARCHAR2(36 CHAR) NOT NULL,
 ACTION_CODE VARCHAR2(80 CHAR) NOT NULL,
 RESOURCE_TYPE VARCHAR2(40 CHAR) NOT NULL,
 RESOURCE_ID VARCHAR2(100 CHAR) NOT NULL,
 REASON_CODE VARCHAR2(160 CHAR),
 OCCURRED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE MBX_BENEFICIARY (
 BENEFICIARY_ID VARCHAR2(36 CHAR) PRIMARY KEY,
 OWNER_USER_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M01_IAM_USER(USER_ID),
 DISPLAY_NAME VARCHAR2(100 CHAR) NOT NULL,
 ACCOUNT_TOKEN VARCHAR2(120 CHAR) NOT NULL,
 BANK_CODE VARCHAR2(11 CHAR) NOT NULL,
 STATUS VARCHAR2(16 CHAR) DEFAULT 'PENDING' NOT NULL CHECK (STATUS IN ('PENDING','ACTIVE','DISABLED')),
 CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 VERIFIED_BY VARCHAR2(36 CHAR),
 VERIFIED_AT TIMESTAMP(6) WITH TIME ZONE
);
CREATE TABLE MBX_TELLER_TILL (
 TILL_ID VARCHAR2(36 CHAR) PRIMARY KEY,
 TELLER_USER_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M01_IAM_USER(USER_ID),
 BRANCH_CODE VARCHAR2(80 CHAR) NOT NULL,
 BUSINESS_DATE DATE NOT NULL,
 CASH_GL_ID NUMBER NOT NULL REFERENCES M05_GL_ACCOUNT(GL_ACCOUNT_ID),
 STATUS VARCHAR2(12 CHAR) DEFAULT 'OPEN' NOT NULL CHECK (STATUS IN ('OPEN','CLOSED')),
 CASH_BALANCE NUMBER(18,2) DEFAULT 0 NOT NULL CHECK (CASH_BALANCE>=0),
 CLOSED_BY VARCHAR2(36 CHAR),
 UNIQUE(TELLER_USER_ID,BUSINESS_DATE)
);
CREATE TABLE MBX_CASH_OPERATION (
 OPERATION_ID VARCHAR2(36 CHAR) PRIMARY KEY,
 REQUEST_KEY VARCHAR2(100 CHAR) NOT NULL,
 ACTOR_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M01_IAM_USER(USER_ID),
 ACCOUNT_ID NUMBER NOT NULL REFERENCES M04_BANK_ACCOUNT(ACCOUNT_ID),
 TILL_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES MBX_TELLER_TILL(TILL_ID),
 DIRECTION VARCHAR2(12 CHAR) NOT NULL CHECK (DIRECTION IN ('DEPOSIT','WITHDRAWAL')),
 AMOUNT NUMBER(18,2) NOT NULL CHECK (AMOUNT>0),
 TXN_ID NUMBER NOT NULL REFERENCES M05_TXN_TRANSACTION_LOG(TXN_ID),
 JOURNAL_ID NUMBER NOT NULL REFERENCES M05_GL_JOURNAL(JOURNAL_ID),
 REQUEST_HASH RAW(32) NOT NULL,
 UNIQUE(ACTOR_ID,REQUEST_KEY)
);
CREATE TABLE MBX_CURRENCY (
 CURRENCY_CODE VARCHAR2(3 CHAR) PRIMARY KEY,
 DISPLAY_NAME VARCHAR2(60 CHAR) NOT NULL,
 DECIMAL_PLACES NUMBER(1) DEFAULT 2 NOT NULL,
 ACTIVE_FLAG CHAR(1) DEFAULT 'Y' NOT NULL CHECK (ACTIVE_FLAG IN ('Y','N'))
);
CREATE TABLE MBX_FX_RATE (
 RATE_ID VARCHAR2(36 CHAR) PRIMARY KEY,
 BASE_CURRENCY VARCHAR2(3 CHAR) NOT NULL REFERENCES MBX_CURRENCY(CURRENCY_CODE),
 QUOTE_CURRENCY VARCHAR2(3 CHAR) NOT NULL REFERENCES MBX_CURRENCY(CURRENCY_CODE),
 BUY_RATE NUMBER(20,8) NOT NULL CHECK (BUY_RATE>0),
 MID_RATE NUMBER(20,8) NOT NULL CHECK (MID_RATE>0),
 SELL_RATE NUMBER(20,8) NOT NULL CHECK (SELL_RATE>0),
 SOURCE_CODE VARCHAR2(80 CHAR) NOT NULL,
 OBSERVED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
 VALID_UNTIL TIMESTAMP(6) WITH TIME ZONE NOT NULL,
 STATUS VARCHAR2(12 CHAR) DEFAULT 'PENDING' NOT NULL CHECK (STATUS IN ('PENDING','APPROVED','REJECTED')),
 MAKER_ID VARCHAR2(36 CHAR) NOT NULL,
 CHECKER_ID VARCHAR2(36 CHAR),
 REASON_TEXT VARCHAR2(300 CHAR) NOT NULL,
 CHECK (BASE_CURRENCY<>QUOTE_CURRENCY AND BUY_RATE<=MID_RATE AND MID_RATE<=SELL_RATE AND VALID_UNTIL>OBSERVED_AT),
 CHECK (CHECKER_ID IS NULL OR CHECKER_ID<>MAKER_ID)
);
