-- Additive approval evidence, bound to an exact account/version and command digest.
CREATE TABLE MBX_OVERRIDE_APPROVAL (
 REQUEST_ID VARCHAR2(60 CHAR) PRIMARY KEY,
 ACCOUNT_ID NUMBER NOT NULL REFERENCES M04_BANK_ACCOUNT(ACCOUNT_ID),
 PRODUCT_VERSION_ID NUMBER NOT NULL REFERENCES M03_PM_PRODUCT_VERSION(PRODUCT_VERSION_ID),
 ACTION_CODE VARCHAR2(12 CHAR) NOT NULL CHECK (ACTION_CODE IN ('LIMIT','INTEREST')),
 COMMAND_HASH RAW(32) NOT NULL,
 COMMAND_JSON CLOB NOT NULL,
 POLICY_ID NUMBER NOT NULL REFERENCES M03_PM_OVERRIDE_POLICY(OVERRIDE_POLICY_ID),
 PROPOSED_VALUE NUMBER(20,8) NOT NULL,
 MAKER_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M01_IAM_USER(USER_ID),
 CHECKER_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M01_IAM_USER(USER_ID),
 STATUS VARCHAR2(12 CHAR) DEFAULT 'PENDING' NOT NULL CHECK (STATUS IN ('PENDING','APPROVED','REJECTED','APPLIED')),
 EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
 CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 DECIDED_AT TIMESTAMP(6) WITH TIME ZONE,
 REASON_TEXT VARCHAR2(300 CHAR),
 CHECK (MAKER_ID<>CHECKER_ID)
);
