-- Apply after 006. Stores only exact, short-lived actions confirmed in the UI.
CREATE TABLE MBX_ASSISTANT_INTENT (
  INTENT_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  ACTOR_USER_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M01_IAM_USER(USER_ID),
  SESSION_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M01_IAM_SESSION(SESSION_ID),
  ACTION_CODE VARCHAR2(40 CHAR) NOT NULL,
  PAYLOAD_JSON VARCHAR2(2000 CHAR) NOT NULL,
  STATUS VARCHAR2(16 CHAR) NOT NULL,
  REQUEST_KEY VARCHAR2(100 CHAR) NOT NULL UNIQUE,
  RESULT_REF VARCHAR2(100 CHAR),
  CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  CONSUMED_AT TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT MBX_ASSISTANT_INTENT_ACTION_CK CHECK (ACTION_CODE IN ('PAYMENT_INITIATE','BENEFICIARY_VERIFY')),
  CONSTRAINT MBX_ASSISTANT_INTENT_STATUS_CK CHECK (STATUS IN ('PENDING','COMPLETED','CANCELLED'))
);
CREATE INDEX MBX_ASSISTANT_INTENT_ACTOR_IX ON MBX_ASSISTANT_INTENT(ACTOR_USER_ID, STATUS, EXPIRES_AT);
