-- Run once with F5 in SQL Developer while connected as the Moneybags schema owner.
-- Safe to rerun: only missing BANK_ADMIN grants are added. This does not touch money.
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_role_id M01_IAM_ROLE.ROLE_ID%TYPE;
  v_status M01_IAM_ROLE.STATUS%TYPE;
  v_added PLS_INTEGER := 0;
  v_permission_id M01_IAM_PERMISSION.PERMISSION_ID%TYPE;
BEGIN
  SELECT ROLE_ID, STATUS INTO v_role_id, v_status
    FROM M01_IAM_ROLE WHERE ROLE_CODE = 'BANK_ADMIN' FOR UPDATE;
  IF v_status <> 'ACTIVE' THEN
    RAISE_APPLICATION_ERROR(-20200, 'BANK_ADMIN role must be active.');
  END IF;

  FOR p IN (
    SELECT 'TREASURY_RECONCILE' AS code, 'TREASURY' AS resource_code FROM dual
    UNION ALL SELECT 'TREASURY_LIQUIDITY_MANAGE', 'TREASURY' FROM dual
    UNION ALL SELECT 'GL_RECONCILE', 'GL' FROM dual
  ) LOOP
    MERGE INTO M01_IAM_PERMISSION target
    USING (SELECT p.code AS code, p.resource_code AS resource_code FROM dual) source
       ON (target.PERMISSION_CODE = source.code)
    WHEN NOT MATCHED THEN INSERT
      (PERMISSION_ID, PERMISSION_CODE, RESOURCE_CODE, ACTION_CODE)
      VALUES (LOWER(RAWTOHEX(SYS_GUID())), source.code, source.resource_code, source.code);

    SELECT PERMISSION_ID INTO v_permission_id
      FROM M01_IAM_PERMISSION WHERE PERMISSION_CODE = p.code;
    INSERT INTO M01_IAM_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID)
      SELECT v_role_id, v_permission_id FROM dual
      WHERE NOT EXISTS (
        SELECT 1 FROM M01_IAM_ROLE_PERMISSION
        WHERE ROLE_ID = v_role_id AND PERMISSION_ID = v_permission_id
      );
    v_added := v_added + SQL%ROWCOUNT;
  END LOOP;

  IF v_added > 0 THEN
    UPDATE M01_IAM_USER
       SET ENTITLEMENT_VERSION = ENTITLEMENT_VERSION + 1,
           ROW_VERSION = ROW_VERSION + 1,
           UPDATED_AT = SYSTIMESTAMP
     WHERE USER_ID IN (
       SELECT USER_ID FROM M01_IAM_USER_ROLE
        WHERE ROLE_ID = v_role_id AND STATUS = 'ACTIVE'
          AND VALID_FROM <= SYSTIMESTAMP
          AND (VALID_TO IS NULL OR VALID_TO > SYSTIMESTAMP)
     );
    INSERT INTO M01_IAM_AUDIT_EVENT
      (AUDIT_ID, EVENT_TYPE, RESOURCE_TYPE, RESOURCE_ID, RESULT, REASON_CODE, CORRELATION_ID)
    VALUES
      (LOWER(RAWTOHEX(SYS_GUID())), 'BANK_ADMIN_TREASURY_GRANTED',
       'IAM_ROLE', v_role_id, 'SUCCESS', 'TREASURY_PERMISSION_MIGRATION',
       LOWER(RAWTOHEX(SYS_GUID())));
  END IF;
END;
/
COMMIT;

SELECT p.PERMISSION_CODE,
       CASE WHEN rp.ROLE_ID IS NULL THEN 'MISSING' ELSE 'GRANTED' END AS BANK_ADMIN_ACCESS
  FROM M01_IAM_PERMISSION p
  JOIN M01_IAM_ROLE r ON r.ROLE_CODE = 'BANK_ADMIN'
  LEFT JOIN M01_IAM_ROLE_PERMISSION rp
    ON rp.PERMISSION_ID = p.PERMISSION_ID AND rp.ROLE_ID = r.ROLE_ID
 WHERE p.PERMISSION_CODE IN
   ('TREASURY_RECONCILE', 'TREASURY_LIQUIDITY_MANAGE', 'GL_RECONCILE')
 ORDER BY p.PERMISSION_CODE;

SELECT u.USERNAME, a.SCOPE_TYPE, a.STATUS AS ASSIGNMENT_STATUS
  FROM M01_IAM_USER u
  JOIN M01_IAM_USER_ROLE a ON a.USER_ID = u.USER_ID
  JOIN M01_IAM_ROLE r ON r.ROLE_ID = a.ROLE_ID
 WHERE r.ROLE_CODE = 'BANK_ADMIN' AND u.STATUS = 'ACTIVE'
   AND a.STATUS = 'ACTIVE' AND a.VALID_FROM <= SYSTIMESTAMP
   AND (a.VALID_TO IS NULL OR a.VALID_TO > SYSTIMESTAMP)
 ORDER BY u.USERNAME;
