-- Run with F5 in SQL Developer as the existing Moneybags schema owner.
-- Idempotent IAM-only migration. No account, journal, payment or reserve data changes.
-- BANK_ADMIN receives every configured permission. BANK_CHECKER receives only
-- read and independent-decision permissions; assigning users remains a separate
-- audited access-request workflow.
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  TYPE code_list IS TABLE OF VARCHAR2(100);
  TYPE code_set IS TABLE OF PLS_INTEGER INDEX BY VARCHAR2(100);
  v_codes code_list := code_list(
    'SYSTEM_SCHEMA_READ','IAM_USER_READ','IAM_AUDIT_READ','CIF_READ',
    'PRODUCT_READ','ACCOUNT_READ','TXN_READ','GL_READ','GL_RECONCILE',
    'PAYMENT_READ','TREASURY_READ','LOAN_READ','STATEMENT_READ',
    'STATEMENT_CATALOG_READ','PRIVACY_PURPOSE_VIEW','PRIVACY_CONSENT_VIEW',
    'PRIVACY_CASE_VIEW','PRIVACY_HOLD_VIEW','PRIVACY_POLICY_VIEW',
    'PRIVACY_AUDIT_VIEW','PRIVACY_EXPORT_VIEW','FX_READ','TELLER_READ',
    'IAM_ACCESS_APPROVE','KYC_REVIEW','PRODUCT_APPROVE','ACCOUNT_APPROVE',
    'TXN_REVERSE_APPROVE','GL_CLOSE_APPROVE','PAYMENT_APPROVE',
    'TREASURY_WORK_APPROVE','LOAN_DECIDE','LOAN_DOCUMENT_VERIFY','LOAN_DISBURSE_APPROVE',
    'TELLER_APPROVE','FX_APPROVE','BENEFICIARY_VERIFY',
    'PRIVACY_PURPOSE_APPROVE','PRIVACY_HOLD_APPROVE',
    'PRIVACY_EXPORT_APPROVE','STATEMENT_APPROVE');
  v_allowed code_set;
  v_admin_id M01_IAM_ROLE.ROLE_ID%TYPE;
  v_checker_id M01_IAM_ROLE.ROLE_ID%TYPE;
  v_permission_id M01_IAM_PERMISSION.PERMISSION_ID%TYPE;
  v_admin_changes PLS_INTEGER := 0;
  v_checker_changes PLS_INTEGER := 0;
BEGIN
  SELECT ROLE_ID INTO v_admin_id FROM M01_IAM_ROLE
   WHERE ROLE_CODE='BANK_ADMIN' AND STATUS='ACTIVE' FOR UPDATE;

  INSERT INTO M01_IAM_ROLE
    (ROLE_ID,ROLE_CODE,DISPLAY_NAME,STATUS,SENSITIVE_FLAG)
  SELECT LOWER(RAWTOHEX(SYS_GUID())),'BANK_CHECKER','Bank Checker','ACTIVE','Y'
    FROM dual WHERE NOT EXISTS
      (SELECT 1 FROM M01_IAM_ROLE WHERE ROLE_CODE='BANK_CHECKER');
  SELECT ROLE_ID INTO v_checker_id FROM M01_IAM_ROLE
   WHERE ROLE_CODE='BANK_CHECKER' AND STATUS='ACTIVE' FOR UPDATE;

  FOR i IN 1..v_codes.COUNT LOOP
    v_allowed(v_codes(i)) := 1;
    MERGE INTO M01_IAM_PERMISSION p
    USING (SELECT v_codes(i) AS code FROM dual) source
       ON (p.PERMISSION_CODE=source.code)
    WHEN NOT MATCHED THEN INSERT
      (PERMISSION_ID,PERMISSION_CODE,RESOURCE_CODE,ACTION_CODE)
      VALUES (LOWER(RAWTOHEX(SYS_GUID())),source.code,
              SUBSTR(source.code,1,INSTR(source.code,'_')-1),source.code);
    SELECT PERMISSION_ID INTO v_permission_id FROM M01_IAM_PERMISSION
     WHERE PERMISSION_CODE=v_codes(i);
    INSERT INTO M01_IAM_ROLE_PERMISSION (ROLE_ID,PERMISSION_ID)
    SELECT v_checker_id,v_permission_id FROM dual WHERE NOT EXISTS
      (SELECT 1 FROM M01_IAM_ROLE_PERMISSION
        WHERE ROLE_ID=v_checker_id AND PERMISSION_ID=v_permission_id);
    v_checker_changes := v_checker_changes + SQL%ROWCOUNT;
  END LOOP;

  -- An earlier hand-made BANK_CHECKER must not retain create/post/manage grants.
  FOR p IN (SELECT p.PERMISSION_ID,p.PERMISSION_CODE
              FROM M01_IAM_ROLE_PERMISSION rp
              JOIN M01_IAM_PERMISSION p ON p.PERMISSION_ID=rp.PERMISSION_ID
             WHERE rp.ROLE_ID=v_checker_id) LOOP
    IF NOT v_allowed.EXISTS(p.PERMISSION_CODE) THEN
      DELETE FROM M01_IAM_ROLE_PERMISSION
       WHERE ROLE_ID=v_checker_id AND PERMISSION_ID=p.PERMISSION_ID;
      v_checker_changes := v_checker_changes + SQL%ROWCOUNT;
    END IF;
  END LOOP;

  -- Includes permissions installed by other teams as well as the new reads.
  INSERT INTO M01_IAM_ROLE_PERMISSION (ROLE_ID,PERMISSION_ID)
  SELECT v_admin_id,p.PERMISSION_ID FROM M01_IAM_PERMISSION p
   WHERE NOT EXISTS (SELECT 1 FROM M01_IAM_ROLE_PERMISSION rp
                     WHERE rp.ROLE_ID=v_admin_id
                       AND rp.PERMISSION_ID=p.PERMISSION_ID);
  v_admin_changes := SQL%ROWCOUNT;

  -- Reuse the bank's existing administrator approval ceilings for the demo
  -- checker. No new amount or rate limit is invented by this migration.
  INSERT INTO M01_IAM_ROLE_AUTHORITY
    (AUTHORITY_ID,ROLE_ID,AUTHORITY_CODE,CURRENCY_CODE,
     MAX_AMOUNT,MAX_RATE_PCT,VALID_FROM,VALID_TO)
  SELECT LOWER(RAWTOHEX(SYS_GUID())),v_checker_id,a.AUTHORITY_CODE,
         a.CURRENCY_CODE,a.MAX_AMOUNT,a.MAX_RATE_PCT,a.VALID_FROM,a.VALID_TO
    FROM M01_IAM_ROLE_AUTHORITY a
   WHERE a.ROLE_ID=v_admin_id
     AND a.VALID_FROM<=SYSTIMESTAMP
     AND (a.VALID_TO IS NULL OR a.VALID_TO>SYSTIMESTAMP)
     AND NOT EXISTS (
       SELECT 1 FROM M01_IAM_ROLE_AUTHORITY c
        WHERE c.ROLE_ID=v_checker_id
          AND c.AUTHORITY_CODE=a.AUTHORITY_CODE
          AND c.CURRENCY_CODE=a.CURRENCY_CODE
          AND c.VALID_FROM_UTC=a.VALID_FROM_UTC);
  v_checker_changes := v_checker_changes + SQL%ROWCOUNT;

  IF v_admin_changes>0 THEN
    UPDATE M01_IAM_USER SET ENTITLEMENT_VERSION=ENTITLEMENT_VERSION+1,
      ROW_VERSION=ROW_VERSION+1,UPDATED_AT=SYSTIMESTAMP
     WHERE USER_ID IN (SELECT USER_ID FROM M01_IAM_USER_ROLE
                       WHERE ROLE_ID=v_admin_id AND STATUS='ACTIVE'
                         AND VALID_FROM<=SYSTIMESTAMP
                         AND (VALID_TO IS NULL OR VALID_TO>SYSTIMESTAMP));
  END IF;
  IF v_checker_changes>0 THEN
    UPDATE M01_IAM_USER SET ENTITLEMENT_VERSION=ENTITLEMENT_VERSION+1,
      ROW_VERSION=ROW_VERSION+1,UPDATED_AT=SYSTIMESTAMP
     WHERE USER_ID IN (SELECT USER_ID FROM M01_IAM_USER_ROLE
                       WHERE ROLE_ID=v_checker_id AND STATUS='ACTIVE'
                         AND VALID_FROM<=SYSTIMESTAMP
                         AND (VALID_TO IS NULL OR VALID_TO>SYSTIMESTAMP));
  END IF;
  IF v_admin_changes+v_checker_changes>0 THEN
    INSERT INTO M01_IAM_AUDIT_EVENT
      (AUDIT_ID,EVENT_TYPE,RESOURCE_TYPE,RESOURCE_ID,RESULT,REASON_CODE,CORRELATION_ID)
    VALUES (LOWER(RAWTOHEX(SYS_GUID())),'BANK_ROLE_PERMISSIONS_SYNCED',
            'IAM_ROLE',v_admin_id,'SUCCESS','BANK_ROLE_MIGRATION',
            LOWER(RAWTOHEX(SYS_GUID())));
  END IF;
END;
/
COMMIT;

SELECT r.ROLE_CODE,COUNT(*) AS PERMISSION_COUNT
  FROM M01_IAM_ROLE r JOIN M01_IAM_ROLE_PERMISSION rp ON rp.ROLE_ID=r.ROLE_ID
 WHERE r.ROLE_CODE IN ('BANK_ADMIN','BANK_CHECKER')
 GROUP BY r.ROLE_CODE ORDER BY r.ROLE_CODE;

SELECT p.PERMISSION_CODE FROM M01_IAM_PERMISSION p
 JOIN M01_IAM_ROLE_PERMISSION rp ON rp.PERMISSION_ID=p.PERMISSION_ID
 JOIN M01_IAM_ROLE r ON r.ROLE_ID=rp.ROLE_ID
 WHERE r.ROLE_CODE='BANK_CHECKER' ORDER BY p.PERMISSION_CODE;
