-- Apply once to an existing Oracle Moneybags schema after 003-integration-extension.sql.
-- Adds branch cash custody and till allocation records. No existing balances or
-- RBI reserve positions are changed by this migration.
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

CREATE TABLE MBX_BRANCH_VAULT (
  BRANCH_CODE VARCHAR2(80 CHAR) PRIMARY KEY,
  VAULT_GL_ID NUMBER(19) NOT NULL REFERENCES M05_GL_ACCOUNT(GL_ACCOUNT_ID),
  CASH_BALANCE NUMBER(18,2) NOT NULL CHECK (CASH_BALANCE >= 0),
  OPENING_EVIDENCE_REF VARCHAR2(160 CHAR) NOT NULL,
  CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE MBX_TILL_ALLOCATION (
  ALLOCATION_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  TILL_ID VARCHAR2(36 CHAR) NOT NULL UNIQUE REFERENCES MBX_TELLER_TILL(TILL_ID),
  BRANCH_CODE VARCHAR2(80 CHAR) NOT NULL REFERENCES MBX_BRANCH_VAULT(BRANCH_CODE),
  VAULT_GL_ID NUMBER(19) NOT NULL REFERENCES M05_GL_ACCOUNT(GL_ACCOUNT_ID),
  TILL_GL_ID NUMBER(19) NOT NULL REFERENCES M05_GL_ACCOUNT(GL_ACCOUNT_ID),
  AMOUNT NUMBER(18,2) NOT NULL CHECK (AMOUNT > 0),
  JOURNAL_ID NUMBER(19) NOT NULL UNIQUE REFERENCES M05_GL_JOURNAL(JOURNAL_ID),
  CREATED_BY VARCHAR2(36 CHAR) NOT NULL,
  CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE MBX_TILL_CASH_RETURN (
  RETURN_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  TILL_ID VARCHAR2(36 CHAR) NOT NULL UNIQUE REFERENCES MBX_TELLER_TILL(TILL_ID),
  BRANCH_CODE VARCHAR2(80 CHAR) NOT NULL REFERENCES MBX_BRANCH_VAULT(BRANCH_CODE),
  AMOUNT NUMBER(18,2) NOT NULL CHECK (AMOUNT > 0),
  JOURNAL_ID NUMBER(19) NOT NULL UNIQUE REFERENCES M05_GL_JOURNAL(JOURNAL_ID),
  CHECKED_BY VARCHAR2(36 CHAR) NOT NULL,
  RETURNED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

COMMIT;
