-- Apply once after 011-teller-vault-allocation.sql as the Moneybags schema owner.
-- Extends the simulated local RBI mirror to distinguish a physical cash delivery
-- from a payment or clearing cycle. No balance changes occur during installation.
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

CREATE TABLE MBX_RBI_CASH_DELIVERY (
  DELIVERY_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  REQUEST_KEY VARCHAR2(120 CHAR) NOT NULL UNIQUE,
  BRANCH_CODE VARCHAR2(80 CHAR) NOT NULL REFERENCES MBX_BRANCH_VAULT(BRANCH_CODE),
  RESERVE_ACCOUNT_ID NUMBER(19) NOT NULL REFERENCES M07_RESERVE_ACCOUNT(RESERVE_ACCOUNT_ID),
  AMOUNT NUMBER(18,2) NOT NULL CHECK (AMOUNT > 0),
  SHIPMENT_REF VARCHAR2(120 CHAR) NOT NULL UNIQUE,
  REQUEST_EVIDENCE_REF VARCHAR2(250 CHAR) NOT NULL,
  RECEIPT_EVIDENCE_REF VARCHAR2(250 CHAR),
  STATUS VARCHAR2(16 CHAR) DEFAULT 'PENDING' NOT NULL
    CHECK (STATUS IN ('PENDING','CONFIRMED','REJECTED')),
  MAKER_ID VARCHAR2(36 CHAR) NOT NULL,
  CHECKER_ID VARCHAR2(36 CHAR),
  TXN_ID NUMBER(19) REFERENCES M05_TXN_TRANSACTION_LOG(TXN_ID),
  JOURNAL_ID NUMBER(19) REFERENCES M05_GL_JOURNAL(JOURNAL_ID),
  EVIDENCE_ID NUMBER(19) REFERENCES M07_SETTLEMENT_EVIDENCE(EVIDENCE_ID),
  TREASURY_ENTRY_ID NUMBER(19) REFERENCES M07_CENTRAL_TREASURY_LEDGER(TREASURY_ENTRY_ID),
  REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  DECIDED_AT TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT MBX_CASH_DELIVERY_SOD CHECK (CHECKER_ID IS NULL OR CHECKER_ID <> MAKER_ID),
  CONSTRAINT MBX_CASH_DELIVERY_STATE CHECK (
    (STATUS='PENDING' AND CHECKER_ID IS NULL AND DECIDED_AT IS NULL
       AND TXN_ID IS NULL AND JOURNAL_ID IS NULL AND EVIDENCE_ID IS NULL
       AND TREASURY_ENTRY_ID IS NULL AND RECEIPT_EVIDENCE_REF IS NULL) OR
    (STATUS='REJECTED' AND CHECKER_ID IS NOT NULL AND DECIDED_AT IS NOT NULL
       AND TXN_ID IS NULL AND JOURNAL_ID IS NULL AND EVIDENCE_ID IS NULL
       AND TREASURY_ENTRY_ID IS NULL) OR
    (STATUS='CONFIRMED' AND CHECKER_ID IS NOT NULL AND DECIDED_AT IS NOT NULL
       AND TXN_ID IS NOT NULL AND JOURNAL_ID IS NOT NULL AND EVIDENCE_ID IS NOT NULL
       AND TREASURY_ENTRY_ID IS NOT NULL AND RECEIPT_EVIDENCE_REF IS NOT NULL))
);
CREATE INDEX MBX_CASH_DELIVERY_IX_STATUS ON MBX_RBI_CASH_DELIVERY(STATUS, REQUESTED_AT);

ALTER TABLE M07_SETTLEMENT_EVIDENCE ADD (CASH_DELIVERY_ID VARCHAR2(36 CHAR));
ALTER TABLE M07_SETTLEMENT_EVIDENCE ADD CONSTRAINT MBX_CASH_EVIDENCE_FK
  FOREIGN KEY (CASH_DELIVERY_ID) REFERENCES MBX_RBI_CASH_DELIVERY(DELIVERY_ID);
CREATE UNIQUE INDEX MBX_CASH_EVIDENCE_UQ ON M07_SETTLEMENT_EVIDENCE(CASH_DELIVERY_ID);
ALTER TABLE M07_SETTLEMENT_EVIDENCE DROP CONSTRAINT MB_CK_SETTLEMENT_EVIDENCE_SCOPE;
ALTER TABLE M07_SETTLEMENT_EVIDENCE ADD CONSTRAINT MB_CK_SETTLEMENT_EVIDENCE_SCOPE CHECK (
  (CASH_DELIVERY_ID IS NULL AND RAIL_CODE <> 'CASH' AND EVIDENCE_TYPE <> 'CASH_DELIVERY' AND
    ((PAYMENT_ID IS NOT NULL AND SETTLEMENT_CYCLE_ID IS NULL) OR
     (PAYMENT_ID IS NULL AND SETTLEMENT_CYCLE_ID IS NOT NULL))) OR
  (CASH_DELIVERY_ID IS NOT NULL AND PAYMENT_ID IS NULL AND SETTLEMENT_CYCLE_ID IS NULL
    AND RAIL_CODE='CASH' AND EVIDENCE_TYPE='CASH_DELIVERY' AND MOVEMENT_SIDE='OUT')
);
ALTER TABLE M07_SETTLEMENT_EVIDENCE DROP CONSTRAINT MB_CK_SETTLEMENT_EVIDENCE_RAIL;
ALTER TABLE M07_SETTLEMENT_EVIDENCE ADD CONSTRAINT MB_CK_SETTLEMENT_EVIDENCE_RAIL
  CHECK (RAIL_CODE IN ('UPI','IMPS','NEFT','RTGS','CASH'));
ALTER TABLE M07_SETTLEMENT_EVIDENCE DROP CONSTRAINT MB_CK_SETTLEMENT_EVIDENCE_TYPE;
ALTER TABLE M07_SETTLEMENT_EVIDENCE ADD CONSTRAINT MB_CK_SETTLEMENT_EVIDENCE_TYPE
  CHECK (EVIDENCE_TYPE IN ('RAIL_CONFIRMATION','CLEARING_CONFIRMATION',
                          'RESERVE_STATEMENT','MANUAL_VERIFICATION','CASH_DELIVERY'));

ALTER TABLE M07_CENTRAL_TREASURY_LEDGER ADD (CASH_DELIVERY_ID VARCHAR2(36 CHAR));
ALTER TABLE M07_CENTRAL_TREASURY_LEDGER ADD CONSTRAINT MBX_CASH_LEDGER_FK
  FOREIGN KEY (CASH_DELIVERY_ID) REFERENCES MBX_RBI_CASH_DELIVERY(DELIVERY_ID);
CREATE UNIQUE INDEX MBX_CASH_LEDGER_UQ ON M07_CENTRAL_TREASURY_LEDGER(CASH_DELIVERY_ID);
ALTER TABLE M07_CENTRAL_TREASURY_LEDGER DROP CONSTRAINT MB_CK_TREASURY_LEDGER_SCOPE;
ALTER TABLE M07_CENTRAL_TREASURY_LEDGER ADD CONSTRAINT MB_CK_TREASURY_LEDGER_SCOPE CHECK (
  (CASH_DELIVERY_ID IS NULL AND RAIL_CODE <> 'CASH' AND
    ((PAYMENT_ID IS NOT NULL AND SETTLEMENT_CYCLE_ID IS NULL) OR
     (PAYMENT_ID IS NULL AND SETTLEMENT_CYCLE_ID IS NOT NULL))) OR
  (CASH_DELIVERY_ID IS NOT NULL AND PAYMENT_ID IS NULL AND SETTLEMENT_CYCLE_ID IS NULL
    AND RAIL_CODE='CASH' AND MOVEMENT_SIDE='OUT')
);
ALTER TABLE M07_CENTRAL_TREASURY_LEDGER DROP CONSTRAINT MB_CK_TREASURY_LEDGER_RAIL;
ALTER TABLE M07_CENTRAL_TREASURY_LEDGER ADD CONSTRAINT MB_CK_TREASURY_LEDGER_RAIL
  CHECK (RAIL_CODE IN ('UPI','IMPS','NEFT','RTGS','CASH'));

COMMIT;
