-- Read-only checks after 012-rbi-cash-delivery.sql. Run with F5 in SQL Developer.
-- No rows are inserted or changed by this file.
SET LINESIZE 220
SET PAGESIZE 100
COLUMN RESERVE_ACCOUNT_CODE FORMAT A22
COLUMN ACCOUNT_STATUS FORMAT A12
COLUMN RECONCILED FORMAT A10

SELECT r.RESERVE_ACCOUNT_ID,
       r.RESERVE_ACCOUNT_CODE,
       r.ACCOUNT_STATUS,
       r.GL_ACCOUNT_ID AS RESERVE_GL_ID,
       NVL((SELECT SUM(CASE WHEN g.ENTRY_SIDE = 'DR' THEN g.AMOUNT ELSE -g.AMOUNT END)
              FROM M05_GL_POSTING g WHERE g.GL_ACCOUNT_ID = r.GL_ACCOUNT_ID), 0) AS GL_BOOKED,
       p.CONFIRMED_BALANCE,
       p.AVAILABLE_BALANCE,
       r.SAFETY_BUFFER_AMOUNT,
       p.AVAILABLE_BALANCE - r.SAFETY_BUFFER_AMOUNT AS SHIPMENT_CAPACITY,
       v.IS_MATCHED AS RECONCILED
  FROM M07_RESERVE_ACCOUNT r
  LEFT JOIN M07_RESERVE_POSITION p ON p.RESERVE_ACCOUNT_ID = r.RESERVE_ACCOUNT_ID
  LEFT JOIN M07_V_RESERVE_POSITION_RECON v ON v.RESERVE_ACCOUNT_ID = r.RESERVE_ACCOUNT_ID
 WHERE r.ACCOUNT_TYPE = 'RBI_CURRENT'
 ORDER BY r.RESERVE_ACCOUNT_ID;

SELECT v.BRANCH_CODE, v.VAULT_GL_ID, v.CASH_BALANCE AS VAULT_CASH,
       NVL((SELECT SUM(CASE WHEN g.ENTRY_SIDE = 'DR' THEN g.AMOUNT ELSE -g.AMOUNT END)
              FROM M05_GL_POSTING g WHERE g.GL_ACCOUNT_ID = v.VAULT_GL_ID), 0) AS GL_BOOKED
  FROM MBX_BRANCH_VAULT v
 ORDER BY v.BRANCH_CODE;

SELECT t.TILL_ID, t.TELLER_USER_ID, t.BRANCH_CODE, t.BUSINESS_DATE,
       t.STATUS, t.CASH_GL_ID, t.CASH_BALANCE
  FROM MBX_TELLER_TILL t
 ORDER BY t.BUSINESS_DATE DESC, t.TILL_ID
 FETCH FIRST 20 ROWS ONLY;
