-- Apply once after 012-rbi-cash-delivery.sql as the Moneybags schema owner.
-- Records each authorized branch-vault to teller-till cash transfer.
-- Installing this table does not change any financial balance.
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

CREATE TABLE MBX_TILL_REPLENISHMENT (
  REPLENISHMENT_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  REQUEST_KEY VARCHAR2(100 CHAR) NOT NULL UNIQUE,
  REQUEST_HASH RAW(32) NOT NULL,
  TILL_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES MBX_TELLER_TILL(TILL_ID),
  BRANCH_CODE VARCHAR2(80 CHAR) NOT NULL REFERENCES MBX_BRANCH_VAULT(BRANCH_CODE),
  AMOUNT NUMBER(18,2) NOT NULL CHECK (AMOUNT > 0),
  TILL_BALANCE_AFTER NUMBER(18,2) NOT NULL CHECK (TILL_BALANCE_AFTER >= 0),
  EVIDENCE_REF VARCHAR2(160 CHAR) NOT NULL,
  TXN_ID NUMBER(19) NOT NULL UNIQUE REFERENCES M05_TXN_TRANSACTION_LOG(TXN_ID),
  JOURNAL_ID NUMBER(19) NOT NULL UNIQUE REFERENCES M05_GL_JOURNAL(JOURNAL_ID),
  APPROVED_BY VARCHAR2(36 CHAR) NOT NULL,
  CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX MBX_TILL_REPLENISH_IX_TILL ON MBX_TILL_REPLENISHMENT(TILL_ID, CREATED_AT);
COMMIT;
