-- Apply once after 012-rbi-cash-delivery.sql as the Moneybags schema owner.
-- Adds a distinct, evidenced opening-capital scope to the simulated RBI mirror.
-- This DDL does not itself create an account or post any balance.
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

CREATE TABLE MBX_RBI_RESERVE_OPENING (
  OPENING_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  REQUEST_KEY VARCHAR2(100 CHAR) NOT NULL UNIQUE,
  RESERVE_ACCOUNT_ID NUMBER(19) NOT NULL REFERENCES M07_RESERVE_ACCOUNT(RESERVE_ACCOUNT_ID),
  EQUITY_GL_ID NUMBER(19) NOT NULL REFERENCES M05_GL_ACCOUNT(GL_ACCOUNT_ID),
  AMOUNT NUMBER(18,2) NOT NULL CHECK (AMOUNT > 0),
  EVIDENCE_REF VARCHAR2(120 CHAR) NOT NULL UNIQUE,
  STATUS VARCHAR2(16 CHAR) DEFAULT 'PENDING' NOT NULL CHECK (STATUS IN ('PENDING','CONFIRMED')),
  MAKER_ID VARCHAR2(36 CHAR) NOT NULL,
  CHECKER_ID VARCHAR2(36 CHAR),
  TXN_ID NUMBER(19) REFERENCES M05_TXN_TRANSACTION_LOG(TXN_ID),
  JOURNAL_ID NUMBER(19) REFERENCES M05_GL_JOURNAL(JOURNAL_ID),
  EVIDENCE_ID NUMBER(19) REFERENCES M07_SETTLEMENT_EVIDENCE(EVIDENCE_ID),
  TREASURY_ENTRY_ID NUMBER(19) REFERENCES M07_CENTRAL_TREASURY_LEDGER(TREASURY_ENTRY_ID),
  REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  DECIDED_AT TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT MBX_RESERVE_OPENING_SOD CHECK (CHECKER_ID IS NULL OR CHECKER_ID <> MAKER_ID),
  CONSTRAINT MBX_RESERVE_OPENING_STATE CHECK (
    (STATUS='PENDING' AND CHECKER_ID IS NULL AND DECIDED_AT IS NULL
      AND TXN_ID IS NULL AND JOURNAL_ID IS NULL AND EVIDENCE_ID IS NULL AND TREASURY_ENTRY_ID IS NULL) OR
    (STATUS='CONFIRMED' AND CHECKER_ID IS NOT NULL AND DECIDED_AT IS NOT NULL
      AND TXN_ID IS NOT NULL AND JOURNAL_ID IS NOT NULL AND EVIDENCE_ID IS NOT NULL AND TREASURY_ENTRY_ID IS NOT NULL)
  )
);

ALTER TABLE M07_SETTLEMENT_EVIDENCE ADD (RESERVE_OPENING_ID VARCHAR2(36 CHAR));
ALTER TABLE M07_SETTLEMENT_EVIDENCE ADD CONSTRAINT MBX_RESERVE_OPENING_EVID_FK
  FOREIGN KEY (RESERVE_OPENING_ID) REFERENCES MBX_RBI_RESERVE_OPENING(OPENING_ID);
CREATE UNIQUE INDEX MBX_RESERVE_OPENING_EVID_UQ ON M07_SETTLEMENT_EVIDENCE(RESERVE_OPENING_ID);
ALTER TABLE M07_SETTLEMENT_EVIDENCE DROP CONSTRAINT MB_CK_SETTLEMENT_EVIDENCE_SCOPE;
ALTER TABLE M07_SETTLEMENT_EVIDENCE ADD CONSTRAINT MB_CK_SETTLEMENT_EVIDENCE_SCOPE CHECK (
  (CASH_DELIVERY_ID IS NULL AND RESERVE_OPENING_ID IS NULL AND RAIL_CODE NOT IN ('CASH','RBI')
    AND EVIDENCE_TYPE NOT IN ('CASH_DELIVERY','RESERVE_OPENING')
    AND ((PAYMENT_ID IS NOT NULL AND SETTLEMENT_CYCLE_ID IS NULL) OR
         (PAYMENT_ID IS NULL AND SETTLEMENT_CYCLE_ID IS NOT NULL))) OR
  (CASH_DELIVERY_ID IS NOT NULL AND RESERVE_OPENING_ID IS NULL
    AND PAYMENT_ID IS NULL AND SETTLEMENT_CYCLE_ID IS NULL
    AND RAIL_CODE='CASH' AND EVIDENCE_TYPE='CASH_DELIVERY' AND MOVEMENT_SIDE='OUT') OR
  (RESERVE_OPENING_ID IS NOT NULL AND CASH_DELIVERY_ID IS NULL
    AND PAYMENT_ID IS NULL AND SETTLEMENT_CYCLE_ID IS NULL
    AND RAIL_CODE='RBI' AND EVIDENCE_TYPE='RESERVE_OPENING' AND MOVEMENT_SIDE='IN')
);
ALTER TABLE M07_SETTLEMENT_EVIDENCE DROP CONSTRAINT MB_CK_SETTLEMENT_EVIDENCE_RAIL;
ALTER TABLE M07_SETTLEMENT_EVIDENCE ADD CONSTRAINT MB_CK_SETTLEMENT_EVIDENCE_RAIL
  CHECK (RAIL_CODE IN ('UPI','IMPS','NEFT','RTGS','CASH','RBI'));
ALTER TABLE M07_SETTLEMENT_EVIDENCE DROP CONSTRAINT MB_CK_SETTLEMENT_EVIDENCE_TYPE;
ALTER TABLE M07_SETTLEMENT_EVIDENCE ADD CONSTRAINT MB_CK_SETTLEMENT_EVIDENCE_TYPE
  CHECK (EVIDENCE_TYPE IN ('RAIL_CONFIRMATION','CLEARING_CONFIRMATION',
    'RESERVE_STATEMENT','MANUAL_VERIFICATION','CASH_DELIVERY','RESERVE_OPENING'));

ALTER TABLE M07_CENTRAL_TREASURY_LEDGER ADD (RESERVE_OPENING_ID VARCHAR2(36 CHAR));
ALTER TABLE M07_CENTRAL_TREASURY_LEDGER ADD CONSTRAINT MBX_RESERVE_OPENING_LEDGER_FK
  FOREIGN KEY (RESERVE_OPENING_ID) REFERENCES MBX_RBI_RESERVE_OPENING(OPENING_ID);
CREATE UNIQUE INDEX MBX_RESERVE_OPENING_LEDGER_UQ ON M07_CENTRAL_TREASURY_LEDGER(RESERVE_OPENING_ID);
ALTER TABLE M07_CENTRAL_TREASURY_LEDGER DROP CONSTRAINT MB_CK_TREASURY_LEDGER_SCOPE;
ALTER TABLE M07_CENTRAL_TREASURY_LEDGER ADD CONSTRAINT MB_CK_TREASURY_LEDGER_SCOPE CHECK (
  (CASH_DELIVERY_ID IS NULL AND RESERVE_OPENING_ID IS NULL AND RAIL_CODE NOT IN ('CASH','RBI')
    AND ((PAYMENT_ID IS NOT NULL AND SETTLEMENT_CYCLE_ID IS NULL) OR
         (PAYMENT_ID IS NULL AND SETTLEMENT_CYCLE_ID IS NOT NULL))) OR
  (CASH_DELIVERY_ID IS NOT NULL AND RESERVE_OPENING_ID IS NULL
    AND PAYMENT_ID IS NULL AND SETTLEMENT_CYCLE_ID IS NULL
    AND RAIL_CODE='CASH' AND MOVEMENT_SIDE='OUT') OR
  (RESERVE_OPENING_ID IS NOT NULL AND CASH_DELIVERY_ID IS NULL
    AND PAYMENT_ID IS NULL AND SETTLEMENT_CYCLE_ID IS NULL
    AND RAIL_CODE='RBI' AND MOVEMENT_SIDE='IN')
);
ALTER TABLE M07_CENTRAL_TREASURY_LEDGER DROP CONSTRAINT MB_CK_TREASURY_LEDGER_RAIL;
ALTER TABLE M07_CENTRAL_TREASURY_LEDGER ADD CONSTRAINT MB_CK_TREASURY_LEDGER_RAIL
  CHECK (RAIL_CODE IN ('UPI','IMPS','NEFT','RTGS','CASH','RBI'));
COMMIT;
