-- Credit card extension. Apply ONCE as the schema owner after migrations 001-014.
-- Formerly named 011-credit-cards.sql on feature/credit-card-service.
-- If that former script is already installed, skip this file and run acceptance/credit-cards.sql.
-- 015 is installation order; M11_CC_* remains the permanent module namespace. Do not rename tables.
-- Oracle DDL commits implicitly: back up and inspect first. Never rerun 001 on existing data.
-- No existing customer balances or journal rows are changed by this migration.
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

CREATE TABLE M11_CC_PRODUCT (
  PRODUCT_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  PRODUCT_CODE VARCHAR2(30 CHAR) NOT NULL,
  PRODUCT_NAME VARCHAR2(120 CHAR) NOT NULL,
  VERSION_NO NUMBER(10) NOT NULL,
  STATUS VARCHAR2(12 CHAR) DEFAULT 'PENDING' NOT NULL,
  CURRENCY_CODE CHAR(3 CHAR) DEFAULT 'INR' NOT NULL,
  MINIMUM_LIMIT NUMBER(18,2) NOT NULL,
  MAXIMUM_LIMIT NUMBER(18,2) NOT NULL,
  ANNUAL_RATE_PCT NUMBER(5,2) NOT NULL,
  MIN_PAYMENT_PCT NUMBER(5,2) NOT NULL,
  MIN_PAYMENT_FLOOR NUMBER(18,2) NOT NULL,
  BILLING_DAY NUMBER(2) NOT NULL,
  PAYMENT_DUE_DAYS NUMBER(2) NOT NULL,
  DESCRIPTION VARCHAR2(1000 CHAR) NOT NULL,
  MAKER_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M01_IAM_USER(USER_ID),
  CHECKER_ID VARCHAR2(36 CHAR) REFERENCES M01_IAM_USER(USER_ID),
  DECISION_REASON VARCHAR2(500 CHAR),
  CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  DECIDED_AT TIMESTAMP(6) WITH TIME ZONE,
  ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT CC_PRODUCT_VERSION_UK UNIQUE(PRODUCT_CODE,VERSION_NO),
  CONSTRAINT CC_PRODUCT_STATUS_CK CHECK(STATUS IN ('PENDING','APPROVED','REJECTED','RETIRED')),
  CONSTRAINT CC_PRODUCT_LIMIT_CK CHECK(MINIMUM_LIMIT>=1000 AND MAXIMUM_LIMIT>=MINIMUM_LIMIT AND MAXIMUM_LIMIT<=10000000),
  CONSTRAINT CC_PRODUCT_TERMS_CK CHECK(ANNUAL_RATE_PCT BETWEEN 0 AND 48 AND MIN_PAYMENT_PCT BETWEEN 1 AND 100 AND MIN_PAYMENT_FLOOR>=0 AND BILLING_DAY BETWEEN 1 AND 28 AND PAYMENT_DUE_DAYS BETWEEN 7 AND 25 AND CURRENCY_CODE='INR' AND VERSION_NO>=1),
  CONSTRAINT CC_PRODUCT_CHECKER_CK CHECK((CHECKER_ID IS NULL OR CHECKER_ID<>MAKER_ID) AND (STATUS='PENDING' OR CHECKER_ID IS NOT NULL))
);

CREATE TABLE M11_CC_APPLICATION (
  APPLICATION_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  PRODUCT_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M11_CC_PRODUCT(PRODUCT_ID),
  CIF_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M02_CIF_CUSTOMER(CIF_ID),
  BRANCH_CODE VARCHAR2(40 CHAR) NOT NULL,
  REPAYMENT_ACCOUNT_ID NUMBER(19) NOT NULL REFERENCES M04_BANK_ACCOUNT(ACCOUNT_ID),
  REQUESTED_LIMIT NUMBER(18,2) NOT NULL,
  APPROVED_LIMIT NUMBER(18,2),
  STATUS VARCHAR2(12 CHAR) DEFAULT 'PENDING' NOT NULL,
  TERMS_ACCEPTED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  MAKER_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M01_IAM_USER(USER_ID),
  CHECKER_ID VARCHAR2(36 CHAR) REFERENCES M01_IAM_USER(USER_ID),
  DECISION_REASON VARCHAR2(500 CHAR),
  CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  DECIDED_AT TIMESTAMP(6) WITH TIME ZONE,
  ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT CC_APPLICATION_STATUS_CK CHECK(STATUS IN ('PENDING','APPROVED','REJECTED','CANCELLED')),
  CONSTRAINT CC_APPLICATION_LIMIT_CK CHECK(REQUESTED_LIMIT>=1000 AND (APPROVED_LIMIT IS NULL OR (APPROVED_LIMIT>=1000 AND APPROVED_LIMIT<=REQUESTED_LIMIT))),
  CONSTRAINT CC_APPLICATION_CHECKER_CK CHECK((CHECKER_ID IS NULL OR CHECKER_ID<>MAKER_ID) AND (STATUS NOT IN ('APPROVED','REJECTED') OR CHECKER_ID IS NOT NULL) AND (STATUS<>'APPROVED' OR APPROVED_LIMIT IS NOT NULL))
);
CREATE INDEX CC_APPLICATION_CIF_IX ON M11_CC_APPLICATION(CIF_ID,STATUS);

CREATE TABLE M11_CC_CARD (
  CARD_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  APPLICATION_ID VARCHAR2(36 CHAR) NOT NULL UNIQUE REFERENCES M11_CC_APPLICATION(APPLICATION_ID),
  PRODUCT_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M11_CC_PRODUCT(PRODUCT_ID),
  CIF_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M02_CIF_CUSTOMER(CIF_ID),
  BRANCH_CODE VARCHAR2(40 CHAR) NOT NULL,
  REPAYMENT_ACCOUNT_ID NUMBER(19) NOT NULL REFERENCES M04_BANK_ACCOUNT(ACCOUNT_ID),
  CARD_REFERENCE VARCHAR2(45 CHAR) NOT NULL UNIQUE,
  DISPLAY_ENDING CHAR(4 CHAR) NOT NULL,
  STATUS VARCHAR2(10 CHAR) DEFAULT 'ISSUED' NOT NULL,
  CREDIT_LIMIT NUMBER(18,2) NOT NULL,
  PRINCIPAL_BALANCE NUMBER(18,2) DEFAULT 0 NOT NULL,
  INTEREST_BALANCE NUMBER(18,2) DEFAULT 0 NOT NULL,
  ACCRUED_INTEREST NUMBER(24,8) DEFAULT 0 NOT NULL,
  LAST_ACCRUAL_DATE DATE NOT NULL,
  NEXT_STATEMENT_DATE DATE NOT NULL,
  LAST_STATEMENT_ENTRY NUMBER(19) DEFAULT 0 NOT NULL,
  ISSUED_DATE DATE NOT NULL,
  EXPIRY_DATE DATE NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT CC_CARD_STATUS_CK CHECK(STATUS IN ('ISSUED','ACTIVE','FROZEN','BLOCKED','CLOSED')),
  CONSTRAINT CC_CARD_BALANCE_CK CHECK(CREDIT_LIMIT>=1000 AND PRINCIPAL_BALANCE>=0 AND INTEREST_BALANCE>=0 AND ACCRUED_INTEREST>=-0.005),
  CONSTRAINT CC_CARD_DATES_CK CHECK(EXPIRY_DATE>ISSUED_DATE AND LAST_ACCRUAL_DATE>=ISSUED_DATE)
);
CREATE INDEX CC_CARD_CIF_IX ON M11_CC_CARD(CIF_ID,STATUS);
CREATE INDEX CC_CARD_ACCOUNT_IX ON M11_CC_CARD(REPAYMENT_ACCOUNT_ID,STATUS);

CREATE TABLE M11_CC_ENTRY (
  ENTRY_ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  CARD_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M11_CC_CARD(CARD_ID),
  ENTRY_TYPE VARCHAR2(12 CHAR) NOT NULL,
  AMOUNT NUMBER(18,2) NOT NULL,
  PRINCIPAL_DELTA NUMBER(18,2) NOT NULL,
  INTEREST_DELTA NUMBER(18,2) NOT NULL,
  DEPOSIT_CREDIT NUMBER(18,2) DEFAULT 0 NOT NULL,
  PRINCIPAL_AFTER NUMBER(18,2) NOT NULL,
  INTEREST_AFTER NUMBER(18,2) NOT NULL,
  DESCRIPTION VARCHAR2(500 CHAR) NOT NULL,
  BUSINESS_DATE DATE NOT NULL,
  TXN_ID NUMBER(19) NOT NULL UNIQUE REFERENCES M05_TXN_TRANSACTION_LOG(TXN_ID),
  JOURNAL_ID NUMBER(19) NOT NULL UNIQUE REFERENCES M05_GL_JOURNAL(JOURNAL_ID),
  REFUND_OF_ENTRY NUMBER(19) UNIQUE REFERENCES M11_CC_ENTRY(ENTRY_ID),
  ACTOR_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M01_IAM_USER(USER_ID),
  CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CC_ENTRY_TYPE_CK CHECK(ENTRY_TYPE IN ('PURCHASE','REFUND','REPAYMENT','INTEREST')),
  CONSTRAINT CC_ENTRY_AMOUNT_CK CHECK(AMOUNT>0 AND PRINCIPAL_AFTER>=0 AND INTEREST_AFTER>=0 AND DEPOSIT_CREDIT>=0),
  CONSTRAINT CC_ENTRY_DELTA_CK CHECK(
    (ENTRY_TYPE='PURCHASE' AND PRINCIPAL_DELTA=AMOUNT AND INTEREST_DELTA=0 AND DEPOSIT_CREDIT=0 AND REFUND_OF_ENTRY IS NULL) OR
    (ENTRY_TYPE='INTEREST' AND INTEREST_DELTA=AMOUNT AND PRINCIPAL_DELTA=0 AND DEPOSIT_CREDIT=0 AND REFUND_OF_ENTRY IS NULL) OR
    (ENTRY_TYPE='REPAYMENT' AND PRINCIPAL_DELTA<=0 AND INTEREST_DELTA<=0 AND PRINCIPAL_DELTA+INTEREST_DELTA=-AMOUNT AND DEPOSIT_CREDIT=0 AND REFUND_OF_ENTRY IS NULL) OR
    (ENTRY_TYPE='REFUND' AND PRINCIPAL_DELTA<=0 AND INTEREST_DELTA=0 AND DEPOSIT_CREDIT-PRINCIPAL_DELTA=AMOUNT AND REFUND_OF_ENTRY IS NOT NULL))
);
CREATE INDEX CC_ENTRY_CARD_IX ON M11_CC_ENTRY(CARD_ID,ENTRY_ID);

CREATE TABLE M11_CC_STATEMENT (
  STATEMENT_ID VARCHAR2(36 CHAR) PRIMARY KEY,
  CARD_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M11_CC_CARD(CARD_ID),
  STATEMENT_DATE DATE NOT NULL,
  DUE_DATE DATE NOT NULL,
  FROM_ENTRY_EXCLUSIVE NUMBER(19) NOT NULL,
  TO_ENTRY_INCLUSIVE NUMBER(19) NOT NULL,
  OPENING_BALANCE NUMBER(18,2) NOT NULL,
  PURCHASE_AMOUNT NUMBER(18,2) NOT NULL,
  REFUND_AMOUNT NUMBER(18,2) NOT NULL,
  REPAYMENT_AMOUNT NUMBER(18,2) NOT NULL,
  INTEREST_AMOUNT NUMBER(18,2) NOT NULL,
  CLOSING_BALANCE NUMBER(18,2) NOT NULL,
  MINIMUM_DUE NUMBER(18,2) NOT NULL,
  CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CC_STATEMENT_DATE_UK UNIQUE(CARD_ID,STATEMENT_DATE),
  CONSTRAINT CC_STATEMENT_BALANCE_CK CHECK(CLOSING_BALANCE=OPENING_BALANCE+PURCHASE_AMOUNT+INTEREST_AMOUNT-REFUND_AMOUNT-REPAYMENT_AMOUNT AND CLOSING_BALANCE>=0 AND MINIMUM_DUE>=0 AND MINIMUM_DUE<=CLOSING_BALANCE),
  CONSTRAINT CC_STATEMENT_DATES_CK CHECK(DUE_DATE>STATEMENT_DATE AND TO_ENTRY_INCLUSIVE>=FROM_ENTRY_EXCLUSIVE)
);

CREATE TABLE M11_CC_REQUEST (
  ACTOR_ID VARCHAR2(36 CHAR) NOT NULL REFERENCES M01_IAM_USER(USER_ID),
  REQUEST_KEY VARCHAR2(100 CHAR) NOT NULL,
  REQUEST_HASH VARCHAR2(64 CHAR) NOT NULL,
  RESPONSE_JSON CLOB NOT NULL,
  CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CC_REQUEST_PK PRIMARY KEY(ACTOR_ID,REQUEST_KEY)
);

ALTER TABLE M05_TXN_TRANSACTION_LOG DROP CONSTRAINT MB_CK_TXN_TYPE;
ALTER TABLE M05_TXN_TRANSACTION_LOG ADD CONSTRAINT MB_CK_TXN_TYPE CHECK (TXN_TYPE IN
 ('OPENING_FUNDING','DEPOSIT','WITHDRAWAL','INTERNAL_TRANSFER','FEE','INTEREST','ADJUSTMENT','REVERSAL','PAYMENT_DEBIT','PAYMENT_REFUND','SETTLEMENT','RETURN','LOAN_DISBURSEMENT','LOAN_REPAYMENT','LOAN_ACCRUAL','LOAN_FEE','LOAN_WAIVER','LOAN_WRITE_OFF','LOAN_SETTLEMENT','CARD_PURCHASE','CARD_REFUND','CARD_REPAYMENT','CARD_INTEREST'));
ALTER TABLE M05_GL_JOURNAL DROP CONSTRAINT MB_CK_GL_JOURNAL_TYPE;
ALTER TABLE M05_GL_JOURNAL ADD CONSTRAINT MB_CK_GL_JOURNAL_TYPE CHECK (JOURNAL_TYPE IN
 ('OPENING_FUNDING','DEPOSIT','WITHDRAWAL','TRANSFER','FEE','INTEREST','ADJUSTMENT','PAYMENT_PROVISIONAL','PAYMENT_REFUND','SETTLEMENT','RETURN','LOAN_DISBURSEMENT','LOAN_REPAYMENT','LOAN_ACCRUAL','LOAN_FEE','LOAN_WAIVER','LOAN_WRITE_OFF','LOAN_SETTLEMENT','CARD_PURCHASE','CARD_REFUND','CARD_REPAYMENT','CARD_INTEREST'));

-- Preserve posted credit card history and issued statement snapshots on Oracle.
CREATE OR REPLACE TRIGGER CC_PRODUCT_TERMS_IMMUTABLE
BEFORE UPDATE OR DELETE ON M11_CC_PRODUCT
BEGIN
  IF DELETING OR UPDATING('PRODUCT_ID') OR UPDATING('PRODUCT_CODE') OR UPDATING('PRODUCT_NAME')
    OR UPDATING('VERSION_NO') OR UPDATING('CURRENCY_CODE') OR UPDATING('MINIMUM_LIMIT')
    OR UPDATING('MAXIMUM_LIMIT') OR UPDATING('ANNUAL_RATE_PCT') OR UPDATING('MIN_PAYMENT_PCT')
    OR UPDATING('MIN_PAYMENT_FLOOR') OR UPDATING('BILLING_DAY') OR UPDATING('PAYMENT_DUE_DAYS')
    OR UPDATING('DESCRIPTION') OR UPDATING('MAKER_ID') THEN
    RAISE_APPLICATION_ERROR(-20060,'Credit card terms are immutable; create a new product version.');
  END IF;
END;
/
CREATE OR REPLACE TRIGGER CC_ENTRY_IMMUTABLE
BEFORE UPDATE OR DELETE ON M11_CC_ENTRY
BEGIN
  RAISE_APPLICATION_ERROR(-20061,'Credit card entries are immutable; post a refund instead.');
END;
/
CREATE OR REPLACE TRIGGER CC_STATEMENT_IMMUTABLE
BEFORE UPDATE OR DELETE ON M11_CC_STATEMENT
BEGIN
  RAISE_APPLICATION_ERROR(-20062,'Issued credit card statements are immutable.');
END;
/

-- Install module permissions and ledger codes without changing user assignments.
DECLARE
  TYPE codes IS TABLE OF VARCHAR2(100);
  v_codes codes := codes('CC_READ','CC_PRODUCT_MANAGE','CC_PRODUCT_APPROVE','CC_APPLY','CC_APPROVE','CC_MANAGE','CC_SPEND','CC_REPAY','CC_SERVICE');
BEGIN
  FOR i IN 1..v_codes.COUNT LOOP
    MERGE INTO M01_IAM_PERMISSION p USING (SELECT v_codes(i) code FROM dual) s ON (p.PERMISSION_CODE=s.code)
    WHEN NOT MATCHED THEN INSERT(PERMISSION_ID,PERMISSION_CODE,RESOURCE_CODE,ACTION_CODE)
      VALUES(LOWER(RAWTOHEX(SYS_GUID())),s.code,'CREDIT_CARD',s.code);
  END LOOP;
  INSERT INTO M01_IAM_ROLE_PERMISSION(ROLE_ID,PERMISSION_ID)
  SELECT r.ROLE_ID,p.PERMISSION_ID FROM M01_IAM_ROLE r CROSS JOIN M01_IAM_PERMISSION p
  WHERE ((r.ROLE_CODE='BANK_ADMIN' AND p.PERMISSION_CODE LIKE 'CC_%')
      OR (r.ROLE_CODE='BANK_CHECKER' AND p.PERMISSION_CODE IN ('CC_READ','CC_APPROVE','CC_PRODUCT_APPROVE'))
      OR (r.ROLE_CODE='RETAIL_CUSTOMER' AND p.PERMISSION_CODE IN ('CC_READ','CC_APPLY','CC_MANAGE','CC_SPEND','CC_REPAY')))
    AND NOT EXISTS(SELECT 1 FROM M01_IAM_ROLE_PERMISSION x WHERE x.ROLE_ID=r.ROLE_ID AND x.PERMISSION_ID=p.PERMISSION_ID);
  -- Entitlement refresh on next request; existing sessions must sign in again.
  UPDATE M01_IAM_USER SET ENTITLEMENT_VERSION=ENTITLEMENT_VERSION+1
    WHERE USER_ID IN (SELECT a.USER_ID FROM M01_IAM_USER_ROLE a JOIN M01_IAM_ROLE r ON r.ROLE_ID=a.ROLE_ID
      WHERE r.ROLE_CODE IN ('BANK_ADMIN','BANK_CHECKER','RETAIL_CUSTOMER'));
  FOR g IN (SELECT 'CC_RECEIVABLE' code,'Credit card receivables' label,'ASSET' class,'DR' side FROM dual
    UNION ALL SELECT 'CC_SETTLEMENT','Simulated card merchant settlement','LIABILITY','CR' FROM dual
    UNION ALL SELECT 'CC_INTEREST','Credit card interest income','INCOME','CR' FROM dual) LOOP
    INSERT INTO M05_GL_ACCOUNT(GL_CODE,GL_NAME,ACCOUNT_CLASS,NORMAL_SIDE)
      SELECT g.code,g.label,g.class,g.side FROM dual WHERE NOT EXISTS(SELECT 1 FROM M05_GL_ACCOUNT WHERE GL_CODE=g.code);
  END LOOP;
END;
/
COMMIT;
-- Grant CC_LIMIT authority (INR, maximum amount and APR) through IAM to the
-- designated approval role using your bank's limits. No production ceiling is inferred.
