-- Install the customer-only loan application permission for an existing Oracle schema.
-- Re-runnable: it adds the catalog entry and grants it to the retail customer role once.
MERGE INTO M01_IAM_PERMISSION P
USING (SELECT 'LOAN_APPLY' CODE FROM DUAL) S
ON (P.PERMISSION_CODE=S.CODE)
WHEN NOT MATCHED THEN INSERT (PERMISSION_ID,PERMISSION_CODE,RESOURCE_CODE,ACTION_CODE)
VALUES (LOWER(RAWTOHEX(SYS_GUID())),S.CODE,'LOAN',S.CODE);

MERGE INTO M01_IAM_ROLE_PERMISSION RP
USING (
  SELECT R.ROLE_ID,P.PERMISSION_ID
  FROM M01_IAM_ROLE R CROSS JOIN M01_IAM_PERMISSION P
  WHERE R.ROLE_CODE='RETAIL_CUSTOMER' AND P.PERMISSION_CODE='LOAN_APPLY'
) S
ON (RP.ROLE_ID=S.ROLE_ID AND RP.PERMISSION_ID=S.PERMISSION_ID)
WHEN NOT MATCHED THEN INSERT (ROLE_ID,PERMISSION_ID)
VALUES (S.ROLE_ID,S.PERMISSION_ID);

COMMIT;
