-- Oracle ALPHA loan readiness for the six currently active web loan products.
-- Review the three GL accounts and the BANK_CHECKER authority limit before running.
-- SQL*Plus: run as the ALPHA schema owner. This script is re-runnable.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET SERVEROUTPUT ON

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM M03_PM_PRODUCT p
    JOIN M03_PM_PRODUCT_VERSION v ON v.PRODUCT_ID=p.PRODUCT_ID
   WHERE p.PRODUCT_TYPE='LOAN' AND v.VERSION_STATE='ACTIVE'
     AND p.PRODUCT_CODE IN (
       'PERSONAL_LOAN_WEB_02','HOME_LOAN_WEB_01','VEHICLE_LOAN_WEB_01',
       'EDUCATION_LOAN_WEB_01','BUSINESS_LOAN_WEB_01','OTHER_LOAN_WEB_01');
  IF v_count<>6 THEN
    RAISE_APPLICATION_ERROR(-20081,'Expected exactly six active web loan versions; review product state first');
  END IF;
  SELECT COUNT(*) INTO v_count FROM M01_IAM_ROLE
   WHERE ROLE_CODE='BANK_CHECKER' AND STATUS='ACTIVE';
  IF v_count<>1 THEN
    RAISE_APPLICATION_ERROR(-20082,'An active BANK_CHECKER role is required');
  END IF;
  SELECT COUNT(*) INTO v_count
    FROM M01_IAM_USER_ROLE a
    JOIN M01_IAM_ROLE r ON r.ROLE_ID=a.ROLE_ID
    JOIN M01_IAM_USER u ON u.USER_ID=a.USER_ID
   WHERE r.ROLE_CODE='BANK_CHECKER' AND a.STATUS='ACTIVE'
     AND a.VALID_FROM<=SYSTIMESTAMP
     AND (a.VALID_TO IS NULL OR a.VALID_TO>SYSTIMESTAMP)
     AND u.USERNAME='checker1';
  IF v_count<>1 THEN
    RAISE_APPLICATION_ERROR(-20086,'Expected checker1 to hold one active BANK_CHECKER assignment');
  END IF;
  SELECT COUNT(*) INTO v_count
    FROM M01_IAM_USER_ROLE a JOIN M01_IAM_ROLE r ON r.ROLE_ID=a.ROLE_ID
   WHERE r.ROLE_CODE='BANK_CHECKER' AND a.STATUS='ACTIVE'
     AND a.VALID_FROM<=SYSTIMESTAMP
     AND (a.VALID_TO IS NULL OR a.VALID_TO>SYSTIMESTAMP);
  IF v_count<>1 THEN
    RAISE_APPLICATION_ERROR(-20087,'BANK_CHECKER has other active assignees; review authority scope first');
  END IF;
END;
/

-- Separate asset accounts keep principal and interest receivables distinct.
MERGE INTO M05_GL_ACCOUNT g
USING (
  SELECT 'MBX_LOAN_PRINCIPAL' code,'Loan principal receivable' gl_name,'ASSET' account_class,'DR' normal_side FROM DUAL
  UNION ALL SELECT 'MBX_LOAN_INTEREST','Loan interest receivable','ASSET','DR' FROM DUAL
  UNION ALL SELECT 'MBX_LOAN_INTEREST_INCOME','Loan interest income','INCOME','CR' FROM DUAL
) s ON (g.GL_CODE=s.code)
WHEN NOT MATCHED THEN INSERT
  (GL_CODE,GL_NAME,ACCOUNT_CLASS,NORMAL_SIDE,CURRENCY_CODE,ACTIVE_FLAG)
  VALUES (s.code,s.gl_name,s.account_class,s.normal_side,'INR','Y');

-- Map each approved, active loan version to its receivable and income accounts.
MERGE INTO M05_GL_PRODUCT_MAPPING m
USING (
  SELECT v.PRODUCT_VERSION_ID, roles.GL_ROLE_CODE, g.GL_ACCOUNT_ID
    FROM M03_PM_PRODUCT p
    JOIN M03_PM_PRODUCT_VERSION v ON v.PRODUCT_ID=p.PRODUCT_ID
    CROSS JOIN (
      SELECT 'LOAN_PRINCIPAL' GL_ROLE_CODE,'MBX_LOAN_PRINCIPAL' GL_CODE FROM DUAL
      UNION ALL SELECT 'LOAN_INTEREST','MBX_LOAN_INTEREST' FROM DUAL
      UNION ALL SELECT 'INTEREST_INCOME','MBX_LOAN_INTEREST_INCOME' FROM DUAL
    ) roles
    JOIN M05_GL_ACCOUNT g ON g.GL_CODE=roles.GL_CODE AND g.ACTIVE_FLAG='Y'
   WHERE p.PRODUCT_TYPE='LOAN' AND v.VERSION_STATE='ACTIVE'
     AND p.PRODUCT_CODE IN (
       'PERSONAL_LOAN_WEB_02','HOME_LOAN_WEB_01','VEHICLE_LOAN_WEB_01',
       'EDUCATION_LOAN_WEB_01','BUSINESS_LOAN_WEB_01','OTHER_LOAN_WEB_01')
) s ON (m.PRODUCT_VERSION_ID=s.PRODUCT_VERSION_ID AND m.POSTING_TYPE='LOAN'
        AND m.GL_ROLE_CODE=s.GL_ROLE_CODE AND m.STATUS='ACTIVE')
WHEN NOT MATCHED THEN INSERT
  (PRODUCT_VERSION_ID,POSTING_TYPE,GL_ROLE_CODE,GL_ACCOUNT_ID,EFFECTIVE_FROM,CREATED_BY)
  VALUES (s.PRODUCT_VERSION_ID,'LOAN',s.GL_ROLE_CODE,s.GL_ACCOUNT_ID,
          TRUNC(SYSDATE),'LOAN_READINESS_MIGRATION');

-- The disbursement and repayment accounts use the same customer liability GL
-- as their existing DEPOSIT posting map.
MERGE INTO M05_GL_PRODUCT_MAPPING m
USING (
  SELECT DISTINCT d.PRODUCT_VERSION_ID,d.GL_ACCOUNT_ID
    FROM M05_GL_PRODUCT_MAPPING d
    JOIN M04_BANK_ACCOUNT a ON a.PRODUCT_VERSION_ID=d.PRODUCT_VERSION_ID
   WHERE d.POSTING_TYPE='DEPOSIT' AND d.GL_ROLE_CODE='CUSTOMER_LIABILITY'
     AND d.STATUS='ACTIVE' AND d.EFFECTIVE_FROM<=SYSDATE
     AND (d.EFFECTIVE_TO IS NULL OR d.EFFECTIVE_TO>=SYSDATE)
     AND a.LIFECYCLE_STATUS='ACTIVE' AND a.CURRENCY_CODE='INR'
) s ON (m.PRODUCT_VERSION_ID=s.PRODUCT_VERSION_ID AND m.POSTING_TYPE='LOAN'
        AND m.GL_ROLE_CODE='CUSTOMER_LIABILITY' AND m.STATUS='ACTIVE')
WHEN NOT MATCHED THEN INSERT
  (PRODUCT_VERSION_ID,POSTING_TYPE,GL_ROLE_CODE,GL_ACCOUNT_ID,EFFECTIVE_FROM,CREATED_BY)
  VALUES (s.PRODUCT_VERSION_ID,'LOAN','CUSTOMER_LIABILITY',s.GL_ACCOUNT_ID,
          TRUNC(SYSDATE),'LOAN_READINESS_MIGRATION');

-- This role currently has one active assignee (checker1). The authority is
-- bounded to INR 5,000,000 and 20% annual rate. The service still enforces
-- distinct maker/checker identities and the role's access scope.
MERGE INTO M01_IAM_ROLE_AUTHORITY a
USING (SELECT ROLE_ID FROM M01_IAM_ROLE
        WHERE ROLE_CODE='BANK_CHECKER' AND STATUS='ACTIVE') s
ON (a.ROLE_ID=s.ROLE_ID AND a.AUTHORITY_CODE='LOAN_SANCTION'
    AND a.CURRENCY_CODE='INR' AND a.VALID_TO IS NULL)
WHEN NOT MATCHED THEN INSERT
  (AUTHORITY_ID,ROLE_ID,AUTHORITY_CODE,CURRENCY_CODE,MAX_AMOUNT,MAX_RATE_PCT,VALID_FROM)
  VALUES (LOWER(RAWTOHEX(SYS_GUID())),s.ROLE_ID,'LOAN_SANCTION','INR',5000000,20,SYSTIMESTAMP);

DECLARE
  v_missing NUMBER;
  v_authority NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_missing FROM (
    SELECT v.PRODUCT_VERSION_ID
      FROM M03_PM_PRODUCT p
      JOIN M03_PM_PRODUCT_VERSION v ON v.PRODUCT_ID=p.PRODUCT_ID
      LEFT JOIN M05_GL_PRODUCT_MAPPING m
        ON m.PRODUCT_VERSION_ID=v.PRODUCT_VERSION_ID AND m.POSTING_TYPE='LOAN'
       AND m.STATUS='ACTIVE' AND m.EFFECTIVE_FROM<=SYSDATE
       AND (m.EFFECTIVE_TO IS NULL OR m.EFFECTIVE_TO>=SYSDATE)
       AND m.GL_ROLE_CODE IN ('LOAN_PRINCIPAL','LOAN_INTEREST','INTEREST_INCOME')
     WHERE p.PRODUCT_TYPE='LOAN' AND v.VERSION_STATE='ACTIVE'
       AND p.PRODUCT_CODE IN (
         'PERSONAL_LOAN_WEB_02','HOME_LOAN_WEB_01','VEHICLE_LOAN_WEB_01',
         'EDUCATION_LOAN_WEB_01','BUSINESS_LOAN_WEB_01','OTHER_LOAN_WEB_01')
     GROUP BY v.PRODUCT_VERSION_ID
    HAVING COUNT(DISTINCT m.GL_ROLE_CODE)<>3
  );
  IF v_missing<>0 THEN
    RAISE_APPLICATION_ERROR(-20083,'A loan version is missing a required GL mapping');
  END IF;
  SELECT COUNT(*) INTO v_missing FROM (
    SELECT DISTINCT a.PRODUCT_VERSION_ID
      FROM M04_BANK_ACCOUNT a
     WHERE a.LIFECYCLE_STATUS='ACTIVE' AND a.CURRENCY_CODE='INR'
       AND NOT EXISTS (
         SELECT 1 FROM M05_GL_PRODUCT_MAPPING m
          WHERE m.PRODUCT_VERSION_ID=a.PRODUCT_VERSION_ID
            AND m.POSTING_TYPE='LOAN' AND m.GL_ROLE_CODE='CUSTOMER_LIABILITY'
            AND m.STATUS='ACTIVE' AND m.EFFECTIVE_FROM<=SYSDATE
            AND (m.EFFECTIVE_TO IS NULL OR m.EFFECTIVE_TO>=SYSDATE))
  );
  IF v_missing<>0 THEN
    RAISE_APPLICATION_ERROR(-20084,'An active INR account version lacks a LOAN liability mapping');
  END IF;
  SELECT COUNT(*) INTO v_authority
    FROM M01_IAM_ROLE_AUTHORITY a JOIN M01_IAM_ROLE r ON r.ROLE_ID=a.ROLE_ID
   WHERE r.ROLE_CODE='BANK_CHECKER' AND a.AUTHORITY_CODE='LOAN_SANCTION'
     AND a.CURRENCY_CODE='INR' AND a.MAX_AMOUNT>=5000000 AND a.MAX_RATE_PCT>=20
     AND a.VALID_FROM<=SYSTIMESTAMP AND (a.VALID_TO IS NULL OR a.VALID_TO>SYSTIMESTAMP);
  IF v_authority<1 THEN
    RAISE_APPLICATION_ERROR(-20085,'The checker loan authority is missing or below the reviewed cap');
  END IF;
  DBMS_OUTPUT.PUT_LINE('Loan GL mappings and checker sanction authority are ready.');
END;
/
COMMIT;
